import * as AntdIcons from '@ant-design/icons';
import React from 'react';

export interface IconCatalogItem {
  name: string;
  /** 中文别名，用于中文搜索 */
  aliases: string[];
  icon: React.ComponentType;
}

export const iconCatalog: readonly IconCatalogItem[] = [
  {
    name: 'AccountBookFilled',
    aliases: ['账户', '账号', '书', '文档', '手册'],
    icon: AntdIcons.AccountBookFilled,
  },
  {
    name: 'AccountBookOutlined',
    aliases: ['账户', '账号', '书', '文档', '手册'],
    icon: AntdIcons.AccountBookOutlined,
  },
  {
    name: 'AccountBookTwoTone',
    aliases: ['账户', '账号', '书', '文档', '手册'],
    icon: AntdIcons.AccountBookTwoTone,
  },
  { name: 'AimOutlined', aliases: ['瞄准', '目标'], icon: AntdIcons.AimOutlined },
  { name: 'AlertFilled', aliases: ['警报', '提醒', '告警'], icon: AntdIcons.AlertFilled },
  { name: 'AlertOutlined', aliases: ['警报', '提醒', '告警'], icon: AntdIcons.AlertOutlined },
  { name: 'AlertTwoTone', aliases: ['警报', '提醒', '告警'], icon: AntdIcons.AlertTwoTone },
  { name: 'AlibabaOutlined', aliases: [], icon: AntdIcons.AlibabaOutlined },
  { name: 'AlignCenterOutlined', aliases: ['对齐'], icon: AntdIcons.AlignCenterOutlined },
  { name: 'AlignLeftOutlined', aliases: ['对齐', '左', '向左'], icon: AntdIcons.AlignLeftOutlined },
  {
    name: 'AlignRightOutlined',
    aliases: ['对齐', '右', '向右'],
    icon: AntdIcons.AlignRightOutlined,
  },
  { name: 'AlipayCircleFilled', aliases: [], icon: AntdIcons.AlipayCircleFilled },
  { name: 'AlipayCircleOutlined', aliases: [], icon: AntdIcons.AlipayCircleOutlined },
  { name: 'AlipayOutlined', aliases: [], icon: AntdIcons.AlipayOutlined },
  { name: 'AlipaySquareFilled', aliases: [], icon: AntdIcons.AlipaySquareFilled },
  { name: 'AliwangwangFilled', aliases: [], icon: AntdIcons.AliwangwangFilled },
  { name: 'AliwangwangOutlined', aliases: [], icon: AntdIcons.AliwangwangOutlined },
  { name: 'AliyunOutlined', aliases: [], icon: AntdIcons.AliyunOutlined },
  { name: 'AmazonCircleFilled', aliases: [], icon: AntdIcons.AmazonCircleFilled },
  { name: 'AmazonOutlined', aliases: [], icon: AntdIcons.AmazonOutlined },
  { name: 'AmazonSquareFilled', aliases: [], icon: AntdIcons.AmazonSquareFilled },
  { name: 'AndroidFilled', aliases: ['安卓', 'Android'], icon: AntdIcons.AndroidFilled },
  { name: 'AndroidOutlined', aliases: ['安卓', 'Android'], icon: AntdIcons.AndroidOutlined },
  {
    name: 'AntCloudOutlined',
    aliases: ['蚂蚁', '云', '云端', '云服务'],
    icon: AntdIcons.AntCloudOutlined,
  },
  { name: 'AntDesignOutlined', aliases: ['蚂蚁'], icon: AntdIcons.AntDesignOutlined },
  { name: 'AnthropicFilled', aliases: [], icon: AntdIcons.AnthropicFilled },
  {
    name: 'ApartmentOutlined',
    aliases: ['组织', '部门', '层级'],
    icon: AntdIcons.ApartmentOutlined,
  },
  { name: 'ApiFilled', aliases: ['接口', 'API'], icon: AntdIcons.ApiFilled },
  { name: 'ApiOutlined', aliases: ['接口', 'API'], icon: AntdIcons.ApiOutlined },
  { name: 'ApiTwoTone', aliases: ['接口', 'API'], icon: AntdIcons.ApiTwoTone },
  { name: 'AppleFilled', aliases: ['苹果', 'Apple'], icon: AntdIcons.AppleFilled },
  { name: 'AppleOutlined', aliases: ['苹果', 'Apple'], icon: AntdIcons.AppleOutlined },
  {
    name: 'AppstoreAddOutlined',
    aliases: ['应用商店', '应用', '应用市场', '添加', '新增', '增加'],
    icon: AntdIcons.AppstoreAddOutlined,
  },
  {
    name: 'AppstoreFilled',
    aliases: ['应用商店', '应用', '应用市场'],
    icon: AntdIcons.AppstoreFilled,
  },
  {
    name: 'AppstoreOutlined',
    aliases: ['应用商店', '应用', '应用市场'],
    icon: AntdIcons.AppstoreOutlined,
  },
  {
    name: 'AppstoreTwoTone',
    aliases: ['应用商店', '应用', '应用市场'],
    icon: AntdIcons.AppstoreTwoTone,
  },
  {
    name: 'AreaChartOutlined',
    aliases: ['区域', '面积', '图表', '统计'],
    icon: AntdIcons.AreaChartOutlined,
  },
  { name: 'ArrowDownOutlined', aliases: ['箭头', '下', '向下'], icon: AntdIcons.ArrowDownOutlined },
  { name: 'ArrowLeftOutlined', aliases: ['箭头', '左', '向左'], icon: AntdIcons.ArrowLeftOutlined },
  {
    name: 'ArrowRightOutlined',
    aliases: ['箭头', '右', '向右'],
    icon: AntdIcons.ArrowRightOutlined,
  },
  { name: 'ArrowUpOutlined', aliases: ['箭头', '上', '向上'], icon: AntdIcons.ArrowUpOutlined },
  { name: 'ArrowsAltOutlined', aliases: [], icon: AntdIcons.ArrowsAltOutlined },
  { name: 'AudioFilled', aliases: ['音频', '声音'], icon: AntdIcons.AudioFilled },
  {
    name: 'AudioMutedOutlined',
    aliases: ['音频', '声音', '静音'],
    icon: AntdIcons.AudioMutedOutlined,
  },
  { name: 'AudioOutlined', aliases: ['音频', '声音'], icon: AntdIcons.AudioOutlined },
  { name: 'AudioTwoTone', aliases: ['音频', '声音'], icon: AntdIcons.AudioTwoTone },
  { name: 'AuditOutlined', aliases: ['审计', '审核'], icon: AntdIcons.AuditOutlined },
  { name: 'BackwardFilled', aliases: ['后退'], icon: AntdIcons.BackwardFilled },
  { name: 'BackwardOutlined', aliases: ['后退'], icon: AntdIcons.BackwardOutlined },
  { name: 'BaiduOutlined', aliases: [], icon: AntdIcons.BaiduOutlined },
  { name: 'BankFilled', aliases: ['银行', '金融'], icon: AntdIcons.BankFilled },
  { name: 'BankOutlined', aliases: ['银行', '金融'], icon: AntdIcons.BankOutlined },
  { name: 'BankTwoTone', aliases: ['银行', '金融'], icon: AntdIcons.BankTwoTone },
  {
    name: 'BarChartOutlined',
    aliases: ['柱状', '条形', '图表', '统计'],
    icon: AntdIcons.BarChartOutlined,
  },
  { name: 'BarcodeOutlined', aliases: ['条形码'], icon: AntdIcons.BarcodeOutlined },
  { name: 'BarsOutlined', aliases: [], icon: AntdIcons.BarsOutlined },
  { name: 'BehanceCircleFilled', aliases: [], icon: AntdIcons.BehanceCircleFilled },
  { name: 'BehanceOutlined', aliases: [], icon: AntdIcons.BehanceOutlined },
  { name: 'BehanceSquareFilled', aliases: [], icon: AntdIcons.BehanceSquareFilled },
  { name: 'BehanceSquareOutlined', aliases: [], icon: AntdIcons.BehanceSquareOutlined },
  { name: 'BellFilled', aliases: ['铃铛', '通知', '提醒'], icon: AntdIcons.BellFilled },
  { name: 'BellOutlined', aliases: ['铃铛', '通知', '提醒'], icon: AntdIcons.BellOutlined },
  { name: 'BellTwoTone', aliases: ['铃铛', '通知', '提醒'], icon: AntdIcons.BellTwoTone },
  { name: 'BgColorsOutlined', aliases: [], icon: AntdIcons.BgColorsOutlined },
  { name: 'BilibiliFilled', aliases: [], icon: AntdIcons.BilibiliFilled },
  { name: 'BilibiliOutlined', aliases: [], icon: AntdIcons.BilibiliOutlined },
  { name: 'BlockOutlined', aliases: ['块', '区块'], icon: AntdIcons.BlockOutlined },
  { name: 'BoldOutlined', aliases: ['加粗', '粗体'], icon: AntdIcons.BoldOutlined },
  { name: 'BookFilled', aliases: ['书', '文档', '手册'], icon: AntdIcons.BookFilled },
  { name: 'BookOutlined', aliases: ['书', '文档', '手册'], icon: AntdIcons.BookOutlined },
  { name: 'BookTwoTone', aliases: ['书', '文档', '手册'], icon: AntdIcons.BookTwoTone },
  { name: 'BorderBottomOutlined', aliases: ['边框'], icon: AntdIcons.BorderBottomOutlined },
  {
    name: 'BorderHorizontalOutlined',
    aliases: ['边框', '水平'],
    icon: AntdIcons.BorderHorizontalOutlined,
  },
  { name: 'BorderInnerOutlined', aliases: ['边框'], icon: AntdIcons.BorderInnerOutlined },
  {
    name: 'BorderLeftOutlined',
    aliases: ['边框', '左', '向左'],
    icon: AntdIcons.BorderLeftOutlined,
  },
  { name: 'BorderOuterOutlined', aliases: ['边框'], icon: AntdIcons.BorderOuterOutlined },
  { name: 'BorderOutlined', aliases: ['边框'], icon: AntdIcons.BorderOutlined },
  {
    name: 'BorderRightOutlined',
    aliases: ['边框', '右', '向右'],
    icon: AntdIcons.BorderRightOutlined,
  },
  { name: 'BorderTopOutlined', aliases: ['边框'], icon: AntdIcons.BorderTopOutlined },
  { name: 'BorderVerticleOutlined', aliases: ['边框'], icon: AntdIcons.BorderVerticleOutlined },
  {
    name: 'BorderlessTableOutlined',
    aliases: ['表格', '数据表'],
    icon: AntdIcons.BorderlessTableOutlined,
  },
  { name: 'BoxPlotFilled', aliases: ['盒子', '箱子'], icon: AntdIcons.BoxPlotFilled },
  { name: 'BoxPlotOutlined', aliases: ['盒子', '箱子'], icon: AntdIcons.BoxPlotOutlined },
  { name: 'BoxPlotTwoTone', aliases: ['盒子', '箱子'], icon: AntdIcons.BoxPlotTwoTone },
  { name: 'BranchesOutlined', aliases: ['分支', '多分支'], icon: AntdIcons.BranchesOutlined },
  { name: 'BugFilled', aliases: ['缺陷', '错误', '问题'], icon: AntdIcons.BugFilled },
  { name: 'BugOutlined', aliases: ['缺陷', '错误', '问题'], icon: AntdIcons.BugOutlined },
  { name: 'BugTwoTone', aliases: ['缺陷', '错误', '问题'], icon: AntdIcons.BugTwoTone },
  { name: 'BuildFilled', aliases: ['构建', '建造'], icon: AntdIcons.BuildFilled },
  { name: 'BuildOutlined', aliases: ['构建', '建造'], icon: AntdIcons.BuildOutlined },
  { name: 'BuildTwoTone', aliases: ['构建', '建造'], icon: AntdIcons.BuildTwoTone },
  { name: 'BulbFilled', aliases: ['灯泡', '想法', '创意'], icon: AntdIcons.BulbFilled },
  { name: 'BulbOutlined', aliases: ['灯泡', '想法', '创意'], icon: AntdIcons.BulbOutlined },
  { name: 'BulbTwoTone', aliases: ['灯泡', '想法', '创意'], icon: AntdIcons.BulbTwoTone },
  { name: 'CalculatorFilled', aliases: ['计算器', '计算'], icon: AntdIcons.CalculatorFilled },
  { name: 'CalculatorOutlined', aliases: ['计算器', '计算'], icon: AntdIcons.CalculatorOutlined },
  { name: 'CalculatorTwoTone', aliases: ['计算器', '计算'], icon: AntdIcons.CalculatorTwoTone },
  { name: 'CalendarFilled', aliases: ['日历', '日期', '时间'], icon: AntdIcons.CalendarFilled },
  { name: 'CalendarOutlined', aliases: ['日历', '日期', '时间'], icon: AntdIcons.CalendarOutlined },
  { name: 'CalendarTwoTone', aliases: ['日历', '日期', '时间'], icon: AntdIcons.CalendarTwoTone },
  { name: 'CameraFilled', aliases: ['相机', '拍照', '摄像'], icon: AntdIcons.CameraFilled },
  { name: 'CameraOutlined', aliases: ['相机', '拍照', '摄像'], icon: AntdIcons.CameraOutlined },
  { name: 'CameraTwoTone', aliases: ['相机', '拍照', '摄像'], icon: AntdIcons.CameraTwoTone },
  { name: 'CarFilled', aliases: ['汽车', '车辆'], icon: AntdIcons.CarFilled },
  { name: 'CarOutlined', aliases: ['汽车', '车辆'], icon: AntdIcons.CarOutlined },
  { name: 'CarTwoTone', aliases: ['汽车', '车辆'], icon: AntdIcons.CarTwoTone },
  { name: 'CaretDownFilled', aliases: ['下', '向下'], icon: AntdIcons.CaretDownFilled },
  { name: 'CaretDownOutlined', aliases: ['下', '向下'], icon: AntdIcons.CaretDownOutlined },
  { name: 'CaretLeftFilled', aliases: ['左', '向左'], icon: AntdIcons.CaretLeftFilled },
  { name: 'CaretLeftOutlined', aliases: ['左', '向左'], icon: AntdIcons.CaretLeftOutlined },
  { name: 'CaretRightFilled', aliases: ['右', '向右'], icon: AntdIcons.CaretRightFilled },
  { name: 'CaretRightOutlined', aliases: ['右', '向右'], icon: AntdIcons.CaretRightOutlined },
  { name: 'CaretUpFilled', aliases: ['上', '向上'], icon: AntdIcons.CaretUpFilled },
  { name: 'CaretUpOutlined', aliases: ['上', '向上'], icon: AntdIcons.CaretUpOutlined },
  { name: 'CarryOutFilled', aliases: ['搬运', '携带'], icon: AntdIcons.CarryOutFilled },
  { name: 'CarryOutOutlined', aliases: ['搬运', '携带'], icon: AntdIcons.CarryOutOutlined },
  { name: 'CarryOutTwoTone', aliases: ['搬运', '携带'], icon: AntdIcons.CarryOutTwoTone },
  {
    name: 'CheckCircleFilled',
    aliases: ['勾选', '确认', '选中'],
    icon: AntdIcons.CheckCircleFilled,
  },
  {
    name: 'CheckCircleOutlined',
    aliases: ['勾选', '确认', '选中'],
    icon: AntdIcons.CheckCircleOutlined,
  },
  {
    name: 'CheckCircleTwoTone',
    aliases: ['勾选', '确认', '选中'],
    icon: AntdIcons.CheckCircleTwoTone,
  },
  { name: 'CheckOutlined', aliases: ['勾选', '确认', '选中'], icon: AntdIcons.CheckOutlined },
  {
    name: 'CheckSquareFilled',
    aliases: ['勾选', '确认', '选中'],
    icon: AntdIcons.CheckSquareFilled,
  },
  {
    name: 'CheckSquareOutlined',
    aliases: ['勾选', '确认', '选中'],
    icon: AntdIcons.CheckSquareOutlined,
  },
  {
    name: 'CheckSquareTwoTone',
    aliases: ['勾选', '确认', '选中'],
    icon: AntdIcons.CheckSquareTwoTone,
  },
  { name: 'ChromeFilled', aliases: ['Chrome浏览器'], icon: AntdIcons.ChromeFilled },
  { name: 'ChromeOutlined', aliases: ['Chrome浏览器'], icon: AntdIcons.ChromeOutlined },
  { name: 'CiCircleFilled', aliases: [], icon: AntdIcons.CiCircleFilled },
  { name: 'CiCircleOutlined', aliases: [], icon: AntdIcons.CiCircleOutlined },
  { name: 'CiCircleTwoTone', aliases: [], icon: AntdIcons.CiCircleTwoTone },
  { name: 'CiOutlined', aliases: [], icon: AntdIcons.CiOutlined },
  { name: 'CiTwoTone', aliases: [], icon: AntdIcons.CiTwoTone },
  { name: 'ClaudeFilled', aliases: [], icon: AntdIcons.ClaudeFilled },
  { name: 'ClearOutlined', aliases: ['清除', '清空'], icon: AntdIcons.ClearOutlined },
  { name: 'ClockCircleFilled', aliases: ['时钟', '时间'], icon: AntdIcons.ClockCircleFilled },
  { name: 'ClockCircleOutlined', aliases: ['时钟', '时间'], icon: AntdIcons.ClockCircleOutlined },
  { name: 'ClockCircleTwoTone', aliases: ['时钟', '时间'], icon: AntdIcons.ClockCircleTwoTone },
  { name: 'CloseCircleFilled', aliases: ['关闭', '删除'], icon: AntdIcons.CloseCircleFilled },
  { name: 'CloseCircleOutlined', aliases: ['关闭', '删除'], icon: AntdIcons.CloseCircleOutlined },
  { name: 'CloseCircleTwoTone', aliases: ['关闭', '删除'], icon: AntdIcons.CloseCircleTwoTone },
  { name: 'CloseOutlined', aliases: ['关闭', '删除'], icon: AntdIcons.CloseOutlined },
  { name: 'CloseSquareFilled', aliases: ['关闭', '删除'], icon: AntdIcons.CloseSquareFilled },
  { name: 'CloseSquareOutlined', aliases: ['关闭', '删除'], icon: AntdIcons.CloseSquareOutlined },
  { name: 'CloseSquareTwoTone', aliases: ['关闭', '删除'], icon: AntdIcons.CloseSquareTwoTone },
  {
    name: 'CloudDownloadOutlined',
    aliases: ['云', '云端', '云服务', '下载'],
    icon: AntdIcons.CloudDownloadOutlined,
  },
  { name: 'CloudFilled', aliases: ['云', '云端', '云服务'], icon: AntdIcons.CloudFilled },
  { name: 'CloudOutlined', aliases: ['云', '云端', '云服务'], icon: AntdIcons.CloudOutlined },
  {
    name: 'CloudServerOutlined',
    aliases: ['云', '云端', '云服务'],
    icon: AntdIcons.CloudServerOutlined,
  },
  {
    name: 'CloudSyncOutlined',
    aliases: ['云', '云端', '云服务', '同步', '刷新'],
    icon: AntdIcons.CloudSyncOutlined,
  },
  { name: 'CloudTwoTone', aliases: ['云', '云端', '云服务'], icon: AntdIcons.CloudTwoTone },
  {
    name: 'CloudUploadOutlined',
    aliases: ['云', '云端', '云服务', '上传'],
    icon: AntdIcons.CloudUploadOutlined,
  },
  { name: 'ClusterOutlined', aliases: ['集群', '集合'], icon: AntdIcons.ClusterOutlined },
  { name: 'CodeFilled', aliases: ['代码', '编程', '开发'], icon: AntdIcons.CodeFilled },
  { name: 'CodeOutlined', aliases: ['代码', '编程', '开发'], icon: AntdIcons.CodeOutlined },
  {
    name: 'CodeSandboxCircleFilled',
    aliases: ['代码', '编程', '开发'],
    icon: AntdIcons.CodeSandboxCircleFilled,
  },
  {
    name: 'CodeSandboxOutlined',
    aliases: ['代码', '编程', '开发'],
    icon: AntdIcons.CodeSandboxOutlined,
  },
  {
    name: 'CodeSandboxSquareFilled',
    aliases: ['代码', '编程', '开发'],
    icon: AntdIcons.CodeSandboxSquareFilled,
  },
  { name: 'CodeTwoTone', aliases: ['代码', '编程', '开发'], icon: AntdIcons.CodeTwoTone },
  { name: 'CodepenCircleFilled', aliases: ['Codepen'], icon: AntdIcons.CodepenCircleFilled },
  { name: 'CodepenCircleOutlined', aliases: ['Codepen'], icon: AntdIcons.CodepenCircleOutlined },
  { name: 'CodepenOutlined', aliases: ['Codepen'], icon: AntdIcons.CodepenOutlined },
  { name: 'CodepenSquareFilled', aliases: ['Codepen'], icon: AntdIcons.CodepenSquareFilled },
  { name: 'CoffeeOutlined', aliases: ['咖啡'], icon: AntdIcons.CoffeeOutlined },
  { name: 'ColumnHeightOutlined', aliases: ['列', '栏'], icon: AntdIcons.ColumnHeightOutlined },
  { name: 'ColumnWidthOutlined', aliases: ['列', '栏'], icon: AntdIcons.ColumnWidthOutlined },
  { name: 'CommentOutlined', aliases: ['评论', '注释'], icon: AntdIcons.CommentOutlined },
  { name: 'CompassFilled', aliases: ['指南针', '导航', '方向'], icon: AntdIcons.CompassFilled },
  { name: 'CompassOutlined', aliases: ['指南针', '导航', '方向'], icon: AntdIcons.CompassOutlined },
  { name: 'CompassTwoTone', aliases: ['指南针', '导航', '方向'], icon: AntdIcons.CompassTwoTone },
  { name: 'CompressOutlined', aliases: ['压缩', '收缩'], icon: AntdIcons.CompressOutlined },
  { name: 'ConsoleSqlOutlined', aliases: ['控制台', '终端'], icon: AntdIcons.ConsoleSqlOutlined },
  { name: 'ContactsFilled', aliases: [], icon: AntdIcons.ContactsFilled },
  { name: 'ContactsOutlined', aliases: [], icon: AntdIcons.ContactsOutlined },
  { name: 'ContactsTwoTone', aliases: [], icon: AntdIcons.ContactsTwoTone },
  { name: 'ContainerFilled', aliases: ['容器', '包含'], icon: AntdIcons.ContainerFilled },
  { name: 'ContainerOutlined', aliases: ['容器', '包含'], icon: AntdIcons.ContainerOutlined },
  { name: 'ContainerTwoTone', aliases: ['容器', '包含'], icon: AntdIcons.ContainerTwoTone },
  { name: 'ControlFilled', aliases: ['控制', '管理'], icon: AntdIcons.ControlFilled },
  { name: 'ControlOutlined', aliases: ['控制', '管理'], icon: AntdIcons.ControlOutlined },
  { name: 'ControlTwoTone', aliases: ['控制', '管理'], icon: AntdIcons.ControlTwoTone },
  { name: 'CopyFilled', aliases: ['复制', '拷贝'], icon: AntdIcons.CopyFilled },
  { name: 'CopyOutlined', aliases: ['复制', '拷贝'], icon: AntdIcons.CopyOutlined },
  { name: 'CopyTwoTone', aliases: ['复制', '拷贝'], icon: AntdIcons.CopyTwoTone },
  { name: 'CopyrightCircleFilled', aliases: ['版权'], icon: AntdIcons.CopyrightCircleFilled },
  { name: 'CopyrightCircleOutlined', aliases: ['版权'], icon: AntdIcons.CopyrightCircleOutlined },
  { name: 'CopyrightCircleTwoTone', aliases: ['版权'], icon: AntdIcons.CopyrightCircleTwoTone },
  { name: 'CopyrightOutlined', aliases: ['版权'], icon: AntdIcons.CopyrightOutlined },
  { name: 'CopyrightTwoTone', aliases: ['版权'], icon: AntdIcons.CopyrightTwoTone },
  { name: 'CreditCardFilled', aliases: ['信用', '积分', '卡片'], icon: AntdIcons.CreditCardFilled },
  {
    name: 'CreditCardOutlined',
    aliases: ['信用', '积分', '卡片'],
    icon: AntdIcons.CreditCardOutlined,
  },
  {
    name: 'CreditCardTwoTone',
    aliases: ['信用', '积分', '卡片'],
    icon: AntdIcons.CreditCardTwoTone,
  },
  { name: 'CrownFilled', aliases: ['皇冠', 'VIP', '顶级'], icon: AntdIcons.CrownFilled },
  { name: 'CrownOutlined', aliases: ['皇冠', 'VIP', '顶级'], icon: AntdIcons.CrownOutlined },
  { name: 'CrownTwoTone', aliases: ['皇冠', 'VIP', '顶级'], icon: AntdIcons.CrownTwoTone },
  {
    name: 'CustomerServiceFilled',
    aliases: ['客户', '用户'],
    icon: AntdIcons.CustomerServiceFilled,
  },
  {
    name: 'CustomerServiceOutlined',
    aliases: ['客户', '用户'],
    icon: AntdIcons.CustomerServiceOutlined,
  },
  {
    name: 'CustomerServiceTwoTone',
    aliases: ['客户', '用户'],
    icon: AntdIcons.CustomerServiceTwoTone,
  },
  { name: 'DashOutlined', aliases: [], icon: AntdIcons.DashOutlined },
  { name: 'DashboardFilled', aliases: ['仪表盘', '看板', '概览'], icon: AntdIcons.DashboardFilled },
  {
    name: 'DashboardOutlined',
    aliases: ['仪表盘', '看板', '概览'],
    icon: AntdIcons.DashboardOutlined,
  },
  {
    name: 'DashboardTwoTone',
    aliases: ['仪表盘', '看板', '概览'],
    icon: AntdIcons.DashboardTwoTone,
  },
  { name: 'DatabaseFilled', aliases: ['数据库'], icon: AntdIcons.DatabaseFilled },
  { name: 'DatabaseOutlined', aliases: ['数据库'], icon: AntdIcons.DatabaseOutlined },
  { name: 'DatabaseTwoTone', aliases: ['数据库'], icon: AntdIcons.DatabaseTwoTone },
  { name: 'DeepSeekFilled', aliases: [], icon: AntdIcons.DeepSeekFilled },
  {
    name: 'DeleteColumnOutlined',
    aliases: ['删除', '移除', '清除', '列', '栏'],
    icon: AntdIcons.DeleteColumnOutlined,
  },
  { name: 'DeleteFilled', aliases: ['删除', '移除', '清除'], icon: AntdIcons.DeleteFilled },
  { name: 'DeleteOutlined', aliases: ['删除', '移除', '清除'], icon: AntdIcons.DeleteOutlined },
  {
    name: 'DeleteRowOutlined',
    aliases: ['删除', '移除', '清除', '行'],
    icon: AntdIcons.DeleteRowOutlined,
  },
  { name: 'DeleteTwoTone', aliases: ['删除', '移除', '清除'], icon: AntdIcons.DeleteTwoTone },
  { name: 'DeliveredProcedureOutlined', aliases: [], icon: AntdIcons.DeliveredProcedureOutlined },
  { name: 'DeploymentUnitOutlined', aliases: [], icon: AntdIcons.DeploymentUnitOutlined },
  { name: 'DesktopOutlined', aliases: ['桌面', '电脑'], icon: AntdIcons.DesktopOutlined },
  { name: 'DiffFilled', aliases: [], icon: AntdIcons.DiffFilled },
  { name: 'DiffOutlined', aliases: [], icon: AntdIcons.DiffOutlined },
  { name: 'DiffTwoTone', aliases: [], icon: AntdIcons.DiffTwoTone },
  { name: 'DingdingOutlined', aliases: ['钉钉'], icon: AntdIcons.DingdingOutlined },
  { name: 'DingtalkCircleFilled', aliases: [], icon: AntdIcons.DingtalkCircleFilled },
  { name: 'DingtalkOutlined', aliases: [], icon: AntdIcons.DingtalkOutlined },
  { name: 'DingtalkSquareFilled', aliases: [], icon: AntdIcons.DingtalkSquareFilled },
  { name: 'DisconnectOutlined', aliases: ['断开', '断链'], icon: AntdIcons.DisconnectOutlined },
  { name: 'DiscordFilled', aliases: [], icon: AntdIcons.DiscordFilled },
  { name: 'DiscordOutlined', aliases: [], icon: AntdIcons.DiscordOutlined },
  { name: 'DislikeFilled', aliases: ['踩', '不喜欢'], icon: AntdIcons.DislikeFilled },
  { name: 'DislikeOutlined', aliases: ['踩', '不喜欢'], icon: AntdIcons.DislikeOutlined },
  { name: 'DislikeTwoTone', aliases: ['踩', '不喜欢'], icon: AntdIcons.DislikeTwoTone },
  { name: 'DockerOutlined', aliases: [], icon: AntdIcons.DockerOutlined },
  {
    name: 'DollarCircleFilled',
    aliases: ['美元', '钱', '金额'],
    icon: AntdIcons.DollarCircleFilled,
  },
  {
    name: 'DollarCircleOutlined',
    aliases: ['美元', '钱', '金额'],
    icon: AntdIcons.DollarCircleOutlined,
  },
  {
    name: 'DollarCircleTwoTone',
    aliases: ['美元', '钱', '金额'],
    icon: AntdIcons.DollarCircleTwoTone,
  },
  { name: 'DollarOutlined', aliases: ['美元', '钱', '金额'], icon: AntdIcons.DollarOutlined },
  { name: 'DollarTwoTone', aliases: ['美元', '钱', '金额'], icon: AntdIcons.DollarTwoTone },
  {
    name: 'DotChartOutlined',
    aliases: ['圆点', '点', '图表', '统计'],
    icon: AntdIcons.DotChartOutlined,
  },
  { name: 'DotNetOutlined', aliases: ['圆点', '点'], icon: AntdIcons.DotNetOutlined },
  { name: 'DoubleLeftOutlined', aliases: ['双', '左', '向左'], icon: AntdIcons.DoubleLeftOutlined },
  {
    name: 'DoubleRightOutlined',
    aliases: ['双', '右', '向右'],
    icon: AntdIcons.DoubleRightOutlined,
  },
  { name: 'DownCircleFilled', aliases: ['下', '向下'], icon: AntdIcons.DownCircleFilled },
  { name: 'DownCircleOutlined', aliases: ['下', '向下'], icon: AntdIcons.DownCircleOutlined },
  { name: 'DownCircleTwoTone', aliases: ['下', '向下'], icon: AntdIcons.DownCircleTwoTone },
  { name: 'DownOutlined', aliases: ['下', '向下'], icon: AntdIcons.DownOutlined },
  { name: 'DownSquareFilled', aliases: ['下', '向下'], icon: AntdIcons.DownSquareFilled },
  { name: 'DownSquareOutlined', aliases: ['下', '向下'], icon: AntdIcons.DownSquareOutlined },
  { name: 'DownSquareTwoTone', aliases: ['下', '向下'], icon: AntdIcons.DownSquareTwoTone },
  { name: 'DownloadOutlined', aliases: ['下载'], icon: AntdIcons.DownloadOutlined },
  { name: 'DragOutlined', aliases: ['拖拽', '移动'], icon: AntdIcons.DragOutlined },
  { name: 'DribbbleCircleFilled', aliases: ['Dribbble'], icon: AntdIcons.DribbbleCircleFilled },
  { name: 'DribbbleOutlined', aliases: ['Dribbble'], icon: AntdIcons.DribbbleOutlined },
  { name: 'DribbbleSquareFilled', aliases: ['Dribbble'], icon: AntdIcons.DribbbleSquareFilled },
  { name: 'DribbbleSquareOutlined', aliases: ['Dribbble'], icon: AntdIcons.DribbbleSquareOutlined },
  { name: 'DropboxCircleFilled', aliases: ['Dropbox'], icon: AntdIcons.DropboxCircleFilled },
  { name: 'DropboxOutlined', aliases: ['Dropbox'], icon: AntdIcons.DropboxOutlined },
  { name: 'DropboxSquareFilled', aliases: ['Dropbox'], icon: AntdIcons.DropboxSquareFilled },
  { name: 'EditFilled', aliases: ['编辑', '修改'], icon: AntdIcons.EditFilled },
  { name: 'EditOutlined', aliases: ['编辑', '修改'], icon: AntdIcons.EditOutlined },
  { name: 'EditTwoTone', aliases: ['编辑', '修改'], icon: AntdIcons.EditTwoTone },
  { name: 'ElevenLabsFilled', aliases: [], icon: AntdIcons.ElevenLabsFilled },
  { name: 'EllipsisOutlined', aliases: ['省略', '更多'], icon: AntdIcons.EllipsisOutlined },
  { name: 'EnterOutlined', aliases: ['进入', '回车'], icon: AntdIcons.EnterOutlined },
  {
    name: 'EnvironmentFilled',
    aliases: ['环境', '地点', '位置', '地址'],
    icon: AntdIcons.EnvironmentFilled,
  },
  {
    name: 'EnvironmentOutlined',
    aliases: ['环境', '地点', '位置', '地址'],
    icon: AntdIcons.EnvironmentOutlined,
  },
  {
    name: 'EnvironmentTwoTone',
    aliases: ['环境', '地点', '位置', '地址'],
    icon: AntdIcons.EnvironmentTwoTone,
  },
  { name: 'EuroCircleFilled', aliases: ['欧元'], icon: AntdIcons.EuroCircleFilled },
  { name: 'EuroCircleOutlined', aliases: ['欧元'], icon: AntdIcons.EuroCircleOutlined },
  { name: 'EuroCircleTwoTone', aliases: ['欧元'], icon: AntdIcons.EuroCircleTwoTone },
  { name: 'EuroOutlined', aliases: ['欧元'], icon: AntdIcons.EuroOutlined },
  { name: 'EuroTwoTone', aliases: ['欧元'], icon: AntdIcons.EuroTwoTone },
  { name: 'ExceptionOutlined', aliases: [], icon: AntdIcons.ExceptionOutlined },
  {
    name: 'ExclamationCircleFilled',
    aliases: ['感叹号', '警告', '注意'],
    icon: AntdIcons.ExclamationCircleFilled,
  },
  {
    name: 'ExclamationCircleOutlined',
    aliases: ['感叹号', '警告', '注意'],
    icon: AntdIcons.ExclamationCircleOutlined,
  },
  {
    name: 'ExclamationCircleTwoTone',
    aliases: ['感叹号', '警告', '注意'],
    icon: AntdIcons.ExclamationCircleTwoTone,
  },
  {
    name: 'ExclamationOutlined',
    aliases: ['感叹号', '警告', '注意'],
    icon: AntdIcons.ExclamationOutlined,
  },
  {
    name: 'ExpandAltOutlined',
    aliases: ['展开', '扩展', '扩大'],
    icon: AntdIcons.ExpandAltOutlined,
  },
  { name: 'ExpandOutlined', aliases: ['展开', '扩展', '扩大'], icon: AntdIcons.ExpandOutlined },
  { name: 'ExperimentFilled', aliases: ['实验', '测试'], icon: AntdIcons.ExperimentFilled },
  { name: 'ExperimentOutlined', aliases: ['实验', '测试'], icon: AntdIcons.ExperimentOutlined },
  { name: 'ExperimentTwoTone', aliases: ['实验', '测试'], icon: AntdIcons.ExperimentTwoTone },
  { name: 'ExportOutlined', aliases: ['导出', '输出'], icon: AntdIcons.ExportOutlined },
  { name: 'EyeFilled', aliases: ['眼睛', '查看', '预览', '可见'], icon: AntdIcons.EyeFilled },
  {
    name: 'EyeInvisibleFilled',
    aliases: ['眼睛', '查看', '预览', '可见', '隐藏', '不可见'],
    icon: AntdIcons.EyeInvisibleFilled,
  },
  {
    name: 'EyeInvisibleOutlined',
    aliases: ['眼睛', '查看', '预览', '可见', '隐藏', '不可见'],
    icon: AntdIcons.EyeInvisibleOutlined,
  },
  {
    name: 'EyeInvisibleTwoTone',
    aliases: ['眼睛', '查看', '预览', '可见', '隐藏', '不可见'],
    icon: AntdIcons.EyeInvisibleTwoTone,
  },
  { name: 'EyeOutlined', aliases: ['眼睛', '查看', '预览', '可见'], icon: AntdIcons.EyeOutlined },
  { name: 'EyeTwoTone', aliases: ['眼睛', '查看', '预览', '可见'], icon: AntdIcons.EyeTwoTone },
  { name: 'FacebookFilled', aliases: ['Facebook'], icon: AntdIcons.FacebookFilled },
  { name: 'FacebookOutlined', aliases: ['Facebook'], icon: AntdIcons.FacebookOutlined },
  { name: 'FallOutlined', aliases: ['下降', '下跌'], icon: AntdIcons.FallOutlined },
  { name: 'FastBackwardFilled', aliases: ['快速', '后退'], icon: AntdIcons.FastBackwardFilled },
  { name: 'FastBackwardOutlined', aliases: ['快速', '后退'], icon: AntdIcons.FastBackwardOutlined },
  { name: 'FastForwardFilled', aliases: ['快速', '前进'], icon: AntdIcons.FastForwardFilled },
  { name: 'FastForwardOutlined', aliases: ['快速', '前进'], icon: AntdIcons.FastForwardOutlined },
  { name: 'FieldBinaryOutlined', aliases: ['字段'], icon: AntdIcons.FieldBinaryOutlined },
  {
    name: 'FieldNumberOutlined',
    aliases: ['字段', '数字', '编号'],
    icon: AntdIcons.FieldNumberOutlined,
  },
  { name: 'FieldStringOutlined', aliases: ['字段'], icon: AntdIcons.FieldStringOutlined },
  { name: 'FieldTimeOutlined', aliases: ['字段'], icon: AntdIcons.FieldTimeOutlined },
  {
    name: 'FileAddFilled',
    aliases: ['文件', '文档', '添加', '新增', '增加'],
    icon: AntdIcons.FileAddFilled,
  },
  {
    name: 'FileAddOutlined',
    aliases: ['文件', '文档', '添加', '新增', '增加'],
    icon: AntdIcons.FileAddOutlined,
  },
  {
    name: 'FileAddTwoTone',
    aliases: ['文件', '文档', '添加', '新增', '增加'],
    icon: AntdIcons.FileAddTwoTone,
  },
  { name: 'FileDoneOutlined', aliases: ['文件', '文档'], icon: AntdIcons.FileDoneOutlined },
  { name: 'FileExcelFilled', aliases: ['文件', '文档'], icon: AntdIcons.FileExcelFilled },
  { name: 'FileExcelOutlined', aliases: ['文件', '文档'], icon: AntdIcons.FileExcelOutlined },
  { name: 'FileExcelTwoTone', aliases: ['文件', '文档'], icon: AntdIcons.FileExcelTwoTone },
  {
    name: 'FileExclamationFilled',
    aliases: ['文件', '文档', '感叹号', '警告', '注意'],
    icon: AntdIcons.FileExclamationFilled,
  },
  {
    name: 'FileExclamationOutlined',
    aliases: ['文件', '文档', '感叹号', '警告', '注意'],
    icon: AntdIcons.FileExclamationOutlined,
  },
  {
    name: 'FileExclamationTwoTone',
    aliases: ['文件', '文档', '感叹号', '警告', '注意'],
    icon: AntdIcons.FileExclamationTwoTone,
  },
  { name: 'FileFilled', aliases: ['文件', '文档'], icon: AntdIcons.FileFilled },
  { name: 'FileGifOutlined', aliases: ['文件', '文档'], icon: AntdIcons.FileGifOutlined },
  {
    name: 'FileImageFilled',
    aliases: ['文件', '文档', '图片', '图像'],
    icon: AntdIcons.FileImageFilled,
  },
  {
    name: 'FileImageOutlined',
    aliases: ['文件', '文档', '图片', '图像'],
    icon: AntdIcons.FileImageOutlined,
  },
  {
    name: 'FileImageTwoTone',
    aliases: ['文件', '文档', '图片', '图像'],
    icon: AntdIcons.FileImageTwoTone,
  },
  { name: 'FileJpgOutlined', aliases: ['文件', '文档'], icon: AntdIcons.FileJpgOutlined },
  { name: 'FileMarkdownFilled', aliases: ['文件', '文档'], icon: AntdIcons.FileMarkdownFilled },
  { name: 'FileMarkdownOutlined', aliases: ['文件', '文档'], icon: AntdIcons.FileMarkdownOutlined },
  { name: 'FileMarkdownTwoTone', aliases: ['文件', '文档'], icon: AntdIcons.FileMarkdownTwoTone },
  { name: 'FileOutlined', aliases: ['文件', '文档'], icon: AntdIcons.FileOutlined },
  { name: 'FilePdfFilled', aliases: ['文件', '文档'], icon: AntdIcons.FilePdfFilled },
  { name: 'FilePdfOutlined', aliases: ['文件', '文档'], icon: AntdIcons.FilePdfOutlined },
  { name: 'FilePdfTwoTone', aliases: ['文件', '文档'], icon: AntdIcons.FilePdfTwoTone },
  { name: 'FilePptFilled', aliases: ['文件', '文档'], icon: AntdIcons.FilePptFilled },
  { name: 'FilePptOutlined', aliases: ['文件', '文档'], icon: AntdIcons.FilePptOutlined },
  { name: 'FilePptTwoTone', aliases: ['文件', '文档'], icon: AntdIcons.FilePptTwoTone },
  { name: 'FileProtectOutlined', aliases: ['文件', '文档'], icon: AntdIcons.FileProtectOutlined },
  {
    name: 'FileSearchOutlined',
    aliases: ['文件', '文档', '搜索', '查找', '查询'],
    icon: AntdIcons.FileSearchOutlined,
  },
  {
    name: 'FileSyncOutlined',
    aliases: ['文件', '文档', '同步', '刷新'],
    icon: AntdIcons.FileSyncOutlined,
  },
  {
    name: 'FileTextFilled',
    aliases: ['文件', '文档', '文本', '文字'],
    icon: AntdIcons.FileTextFilled,
  },
  {
    name: 'FileTextOutlined',
    aliases: ['文件', '文档', '文本', '文字'],
    icon: AntdIcons.FileTextOutlined,
  },
  {
    name: 'FileTextTwoTone',
    aliases: ['文件', '文档', '文本', '文字'],
    icon: AntdIcons.FileTextTwoTone,
  },
  { name: 'FileTwoTone', aliases: ['文件', '文档'], icon: AntdIcons.FileTwoTone },
  { name: 'FileUnknownFilled', aliases: ['文件', '文档'], icon: AntdIcons.FileUnknownFilled },
  { name: 'FileUnknownOutlined', aliases: ['文件', '文档'], icon: AntdIcons.FileUnknownOutlined },
  { name: 'FileUnknownTwoTone', aliases: ['文件', '文档'], icon: AntdIcons.FileUnknownTwoTone },
  { name: 'FileWordFilled', aliases: ['文件', '文档'], icon: AntdIcons.FileWordFilled },
  { name: 'FileWordOutlined', aliases: ['文件', '文档'], icon: AntdIcons.FileWordOutlined },
  { name: 'FileWordTwoTone', aliases: ['文件', '文档'], icon: AntdIcons.FileWordTwoTone },
  { name: 'FileZipFilled', aliases: ['文件', '文档'], icon: AntdIcons.FileZipFilled },
  { name: 'FileZipOutlined', aliases: ['文件', '文档'], icon: AntdIcons.FileZipOutlined },
  { name: 'FileZipTwoTone', aliases: ['文件', '文档'], icon: AntdIcons.FileZipTwoTone },
  { name: 'FilterFilled', aliases: ['筛选', '过滤'], icon: AntdIcons.FilterFilled },
  { name: 'FilterOutlined', aliases: ['筛选', '过滤'], icon: AntdIcons.FilterOutlined },
  { name: 'FilterTwoTone', aliases: ['筛选', '过滤'], icon: AntdIcons.FilterTwoTone },
  { name: 'FireFilled', aliases: ['火', '热门', '热'], icon: AntdIcons.FireFilled },
  { name: 'FireOutlined', aliases: ['火', '热门', '热'], icon: AntdIcons.FireOutlined },
  { name: 'FireTwoTone', aliases: ['火', '热门', '热'], icon: AntdIcons.FireTwoTone },
  { name: 'FlagFilled', aliases: ['旗帜', '标记'], icon: AntdIcons.FlagFilled },
  { name: 'FlagOutlined', aliases: ['旗帜', '标记'], icon: AntdIcons.FlagOutlined },
  { name: 'FlagTwoTone', aliases: ['旗帜', '标记'], icon: AntdIcons.FlagTwoTone },
  {
    name: 'FolderAddFilled',
    aliases: ['文件夹', '目录', '添加', '新增', '增加'],
    icon: AntdIcons.FolderAddFilled,
  },
  {
    name: 'FolderAddOutlined',
    aliases: ['文件夹', '目录', '添加', '新增', '增加'],
    icon: AntdIcons.FolderAddOutlined,
  },
  {
    name: 'FolderAddTwoTone',
    aliases: ['文件夹', '目录', '添加', '新增', '增加'],
    icon: AntdIcons.FolderAddTwoTone,
  },
  { name: 'FolderFilled', aliases: ['文件夹', '目录'], icon: AntdIcons.FolderFilled },
  { name: 'FolderOpenFilled', aliases: ['文件夹', '目录'], icon: AntdIcons.FolderOpenFilled },
  { name: 'FolderOpenOutlined', aliases: ['文件夹', '目录'], icon: AntdIcons.FolderOpenOutlined },
  { name: 'FolderOpenTwoTone', aliases: ['文件夹', '目录'], icon: AntdIcons.FolderOpenTwoTone },
  { name: 'FolderOutlined', aliases: ['文件夹', '目录'], icon: AntdIcons.FolderOutlined },
  { name: 'FolderTwoTone', aliases: ['文件夹', '目录'], icon: AntdIcons.FolderTwoTone },
  { name: 'FolderViewOutlined', aliases: ['文件夹', '目录'], icon: AntdIcons.FolderViewOutlined },
  { name: 'FontColorsOutlined', aliases: ['字体', '文字'], icon: AntdIcons.FontColorsOutlined },
  { name: 'FontSizeOutlined', aliases: ['字体', '文字'], icon: AntdIcons.FontSizeOutlined },
  { name: 'ForkOutlined', aliases: ['分叉'], icon: AntdIcons.ForkOutlined },
  { name: 'FormOutlined', aliases: ['表单', '表格'], icon: AntdIcons.FormOutlined },
  { name: 'FormatPainterFilled', aliases: [], icon: AntdIcons.FormatPainterFilled },
  { name: 'FormatPainterOutlined', aliases: [], icon: AntdIcons.FormatPainterOutlined },
  { name: 'ForwardFilled', aliases: ['前进'], icon: AntdIcons.ForwardFilled },
  { name: 'ForwardOutlined', aliases: ['前进'], icon: AntdIcons.ForwardOutlined },
  { name: 'FrownFilled', aliases: ['皱眉', '不满', '难过'], icon: AntdIcons.FrownFilled },
  { name: 'FrownOutlined', aliases: ['皱眉', '不满', '难过'], icon: AntdIcons.FrownOutlined },
  { name: 'FrownTwoTone', aliases: ['皱眉', '不满', '难过'], icon: AntdIcons.FrownTwoTone },
  { name: 'FullscreenExitOutlined', aliases: ['全屏'], icon: AntdIcons.FullscreenExitOutlined },
  { name: 'FullscreenOutlined', aliases: ['全屏'], icon: AntdIcons.FullscreenOutlined },
  { name: 'FunctionOutlined', aliases: [], icon: AntdIcons.FunctionOutlined },
  { name: 'FundFilled', aliases: ['基金', '资金', '财务'], icon: AntdIcons.FundFilled },
  { name: 'FundOutlined', aliases: ['基金', '资金', '财务'], icon: AntdIcons.FundOutlined },
  {
    name: 'FundProjectionScreenOutlined',
    aliases: ['基金', '资金', '财务'],
    icon: AntdIcons.FundProjectionScreenOutlined,
  },
  { name: 'FundTwoTone', aliases: ['基金', '资金', '财务'], icon: AntdIcons.FundTwoTone },
  { name: 'FundViewOutlined', aliases: ['基金', '资金', '财务'], icon: AntdIcons.FundViewOutlined },
  { name: 'FunnelPlotFilled', aliases: [], icon: AntdIcons.FunnelPlotFilled },
  { name: 'FunnelPlotOutlined', aliases: [], icon: AntdIcons.FunnelPlotOutlined },
  { name: 'FunnelPlotTwoTone', aliases: [], icon: AntdIcons.FunnelPlotTwoTone },
  { name: 'GatewayOutlined', aliases: ['网关'], icon: AntdIcons.GatewayOutlined },
  { name: 'GeminiFilled', aliases: [], icon: AntdIcons.GeminiFilled },
  { name: 'GifOutlined', aliases: [], icon: AntdIcons.GifOutlined },
  { name: 'GiftFilled', aliases: ['礼物', '礼品'], icon: AntdIcons.GiftFilled },
  { name: 'GiftOutlined', aliases: ['礼物', '礼品'], icon: AntdIcons.GiftOutlined },
  { name: 'GiftTwoTone', aliases: ['礼物', '礼品'], icon: AntdIcons.GiftTwoTone },
  { name: 'GithubFilled', aliases: ['GitHub'], icon: AntdIcons.GithubFilled },
  { name: 'GithubOutlined', aliases: ['GitHub'], icon: AntdIcons.GithubOutlined },
  { name: 'GitlabFilled', aliases: ['GitLab'], icon: AntdIcons.GitlabFilled },
  { name: 'GitlabOutlined', aliases: ['GitLab'], icon: AntdIcons.GitlabOutlined },
  {
    name: 'GlobalOutlined',
    aliases: ['全球', '国际', '语言', '地球'],
    icon: AntdIcons.GlobalOutlined,
  },
  { name: 'GoldFilled', aliases: ['金', '黄金'], icon: AntdIcons.GoldFilled },
  { name: 'GoldOutlined', aliases: ['金', '黄金'], icon: AntdIcons.GoldOutlined },
  { name: 'GoldTwoTone', aliases: ['金', '黄金'], icon: AntdIcons.GoldTwoTone },
  { name: 'GoldenFilled', aliases: [], icon: AntdIcons.GoldenFilled },
  { name: 'GoogleCircleFilled', aliases: ['Google'], icon: AntdIcons.GoogleCircleFilled },
  { name: 'GoogleOutlined', aliases: ['Google'], icon: AntdIcons.GoogleOutlined },
  {
    name: 'GooglePlusCircleFilled',
    aliases: ['Google', '添加', '加号', '新增', '增加'],
    icon: AntdIcons.GooglePlusCircleFilled,
  },
  {
    name: 'GooglePlusOutlined',
    aliases: ['Google', '添加', '加号', '新增', '增加'],
    icon: AntdIcons.GooglePlusOutlined,
  },
  {
    name: 'GooglePlusSquareFilled',
    aliases: ['Google', '添加', '加号', '新增', '增加'],
    icon: AntdIcons.GooglePlusSquareFilled,
  },
  { name: 'GoogleSquareFilled', aliases: ['Google'], icon: AntdIcons.GoogleSquareFilled },
  { name: 'GroupOutlined', aliases: ['分组', '群组'], icon: AntdIcons.GroupOutlined },
  { name: 'HarmonyOSOutlined', aliases: [], icon: AntdIcons.HarmonyOSOutlined },
  { name: 'HddFilled', aliases: ['硬盘', '存储'], icon: AntdIcons.HddFilled },
  { name: 'HddOutlined', aliases: ['硬盘', '存储'], icon: AntdIcons.HddOutlined },
  { name: 'HddTwoTone', aliases: ['硬盘', '存储'], icon: AntdIcons.HddTwoTone },
  { name: 'HeartFilled', aliases: ['心', '喜欢', '收藏'], icon: AntdIcons.HeartFilled },
  { name: 'HeartOutlined', aliases: ['心', '喜欢', '收藏'], icon: AntdIcons.HeartOutlined },
  { name: 'HeartTwoTone', aliases: ['心', '喜欢', '收藏'], icon: AntdIcons.HeartTwoTone },
  { name: 'HeatMapOutlined', aliases: ['热力', '热图'], icon: AntdIcons.HeatMapOutlined },
  { name: 'HighlightFilled', aliases: ['高亮', '强调'], icon: AntdIcons.HighlightFilled },
  { name: 'HighlightOutlined', aliases: ['高亮', '强调'], icon: AntdIcons.HighlightOutlined },
  { name: 'HighlightTwoTone', aliases: ['高亮', '强调'], icon: AntdIcons.HighlightTwoTone },
  { name: 'HistoryOutlined', aliases: ['历史', '记录'], icon: AntdIcons.HistoryOutlined },
  { name: 'HolderOutlined', aliases: [], icon: AntdIcons.HolderOutlined },
  { name: 'HomeFilled', aliases: ['首页', '主页', '家'], icon: AntdIcons.HomeFilled },
  { name: 'HomeOutlined', aliases: ['首页', '主页', '家'], icon: AntdIcons.HomeOutlined },
  { name: 'HomeTwoTone', aliases: ['首页', '主页', '家'], icon: AntdIcons.HomeTwoTone },
  { name: 'HourglassFilled', aliases: [], icon: AntdIcons.HourglassFilled },
  { name: 'HourglassOutlined', aliases: [], icon: AntdIcons.HourglassOutlined },
  { name: 'HourglassTwoTone', aliases: [], icon: AntdIcons.HourglassTwoTone },
  { name: 'Html5Filled', aliases: [], icon: AntdIcons.Html5Filled },
  { name: 'Html5Outlined', aliases: [], icon: AntdIcons.Html5Outlined },
  { name: 'Html5TwoTone', aliases: [], icon: AntdIcons.Html5TwoTone },
  { name: 'HuggingFaceFilled', aliases: [], icon: AntdIcons.HuggingFaceFilled },
  { name: 'IdcardFilled', aliases: [], icon: AntdIcons.IdcardFilled },
  { name: 'IdcardOutlined', aliases: [], icon: AntdIcons.IdcardOutlined },
  { name: 'IdcardTwoTone', aliases: [], icon: AntdIcons.IdcardTwoTone },
  { name: 'IeCircleFilled', aliases: ['IE浏览器'], icon: AntdIcons.IeCircleFilled },
  { name: 'IeOutlined', aliases: ['IE浏览器'], icon: AntdIcons.IeOutlined },
  { name: 'IeSquareFilled', aliases: ['IE浏览器'], icon: AntdIcons.IeSquareFilled },
  { name: 'ImportOutlined', aliases: ['导入', '引入'], icon: AntdIcons.ImportOutlined },
  { name: 'InboxOutlined', aliases: ['收件箱', '邮件'], icon: AntdIcons.InboxOutlined },
  { name: 'InfoCircleFilled', aliases: ['信息', '详情'], icon: AntdIcons.InfoCircleFilled },
  { name: 'InfoCircleOutlined', aliases: ['信息', '详情'], icon: AntdIcons.InfoCircleOutlined },
  { name: 'InfoCircleTwoTone', aliases: ['信息', '详情'], icon: AntdIcons.InfoCircleTwoTone },
  { name: 'InfoOutlined', aliases: ['信息', '详情'], icon: AntdIcons.InfoOutlined },
  {
    name: 'InsertRowAboveOutlined',
    aliases: ['插入', '行'],
    icon: AntdIcons.InsertRowAboveOutlined,
  },
  {
    name: 'InsertRowBelowOutlined',
    aliases: ['插入', '行'],
    icon: AntdIcons.InsertRowBelowOutlined,
  },
  {
    name: 'InsertRowLeftOutlined',
    aliases: ['插入', '行', '左', '向左'],
    icon: AntdIcons.InsertRowLeftOutlined,
  },
  {
    name: 'InsertRowRightOutlined',
    aliases: ['插入', '行', '右', '向右'],
    icon: AntdIcons.InsertRowRightOutlined,
  },
  { name: 'InstagramFilled', aliases: ['Instagram'], icon: AntdIcons.InstagramFilled },
  { name: 'InstagramOutlined', aliases: ['Instagram'], icon: AntdIcons.InstagramOutlined },
  { name: 'InsuranceFilled', aliases: ['保险'], icon: AntdIcons.InsuranceFilled },
  { name: 'InsuranceOutlined', aliases: ['保险'], icon: AntdIcons.InsuranceOutlined },
  { name: 'InsuranceTwoTone', aliases: ['保险'], icon: AntdIcons.InsuranceTwoTone },
  { name: 'InteractionFilled', aliases: ['交互', '互动'], icon: AntdIcons.InteractionFilled },
  { name: 'InteractionOutlined', aliases: ['交互', '互动'], icon: AntdIcons.InteractionOutlined },
  { name: 'InteractionTwoTone', aliases: ['交互', '互动'], icon: AntdIcons.InteractionTwoTone },
  { name: 'IssuesCloseOutlined', aliases: ['关闭', '删除'], icon: AntdIcons.IssuesCloseOutlined },
  { name: 'ItalicOutlined', aliases: ['斜体'], icon: AntdIcons.ItalicOutlined },
  { name: 'JavaOutlined', aliases: [], icon: AntdIcons.JavaOutlined },
  { name: 'JavaScriptOutlined', aliases: [], icon: AntdIcons.JavaScriptOutlined },
  { name: 'KeyOutlined', aliases: ['钥匙', '权限', '密钥'], icon: AntdIcons.KeyOutlined },
  { name: 'KubernetesOutlined', aliases: [], icon: AntdIcons.KubernetesOutlined },
  { name: 'LaptopOutlined', aliases: ['笔记本', '电脑'], icon: AntdIcons.LaptopOutlined },
  { name: 'LayoutFilled', aliases: ['布局', '版式'], icon: AntdIcons.LayoutFilled },
  { name: 'LayoutOutlined', aliases: ['布局', '版式'], icon: AntdIcons.LayoutOutlined },
  { name: 'LayoutTwoTone', aliases: ['布局', '版式'], icon: AntdIcons.LayoutTwoTone },
  { name: 'LeftCircleFilled', aliases: ['左', '向左'], icon: AntdIcons.LeftCircleFilled },
  { name: 'LeftCircleOutlined', aliases: ['左', '向左'], icon: AntdIcons.LeftCircleOutlined },
  { name: 'LeftCircleTwoTone', aliases: ['左', '向左'], icon: AntdIcons.LeftCircleTwoTone },
  { name: 'LeftOutlined', aliases: ['左', '向左'], icon: AntdIcons.LeftOutlined },
  { name: 'LeftSquareFilled', aliases: ['左', '向左'], icon: AntdIcons.LeftSquareFilled },
  { name: 'LeftSquareOutlined', aliases: ['左', '向左'], icon: AntdIcons.LeftSquareOutlined },
  { name: 'LeftSquareTwoTone', aliases: ['左', '向左'], icon: AntdIcons.LeftSquareTwoTone },
  { name: 'LikeFilled', aliases: ['点赞', '喜欢'], icon: AntdIcons.LikeFilled },
  { name: 'LikeOutlined', aliases: ['点赞', '喜欢'], icon: AntdIcons.LikeOutlined },
  { name: 'LikeTwoTone', aliases: ['点赞', '喜欢'], icon: AntdIcons.LikeTwoTone },
  {
    name: 'LineChartOutlined',
    aliases: ['线条', '折线', '图表', '统计'],
    icon: AntdIcons.LineChartOutlined,
  },
  { name: 'LineHeightOutlined', aliases: ['线条', '折线'], icon: AntdIcons.LineHeightOutlined },
  { name: 'LineOutlined', aliases: ['线条', '折线'], icon: AntdIcons.LineOutlined },
  { name: 'LinkOutlined', aliases: ['链接', '关联'], icon: AntdIcons.LinkOutlined },
  { name: 'LinkedinFilled', aliases: ['LinkedIn'], icon: AntdIcons.LinkedinFilled },
  { name: 'LinkedinOutlined', aliases: ['LinkedIn'], icon: AntdIcons.LinkedinOutlined },
  { name: 'LinuxOutlined', aliases: ['Linux'], icon: AntdIcons.LinuxOutlined },
  { name: 'Loading3QuartersOutlined', aliases: [], icon: AntdIcons.Loading3QuartersOutlined },
  { name: 'LoadingOutlined', aliases: ['加载', '加载中'], icon: AntdIcons.LoadingOutlined },
  { name: 'LockFilled', aliases: ['锁', '加锁', '安全'], icon: AntdIcons.LockFilled },
  { name: 'LockOutlined', aliases: ['锁', '加锁', '安全'], icon: AntdIcons.LockOutlined },
  { name: 'LockTwoTone', aliases: ['锁', '加锁', '安全'], icon: AntdIcons.LockTwoTone },
  { name: 'LoginOutlined', aliases: ['登录'], icon: AntdIcons.LoginOutlined },
  { name: 'LogoutOutlined', aliases: ['登出', '退出'], icon: AntdIcons.LogoutOutlined },
  { name: 'MacCommandFilled', aliases: [], icon: AntdIcons.MacCommandFilled },
  { name: 'MacCommandOutlined', aliases: [], icon: AntdIcons.MacCommandOutlined },
  { name: 'MailFilled', aliases: ['邮件', '邮箱'], icon: AntdIcons.MailFilled },
  { name: 'MailOutlined', aliases: ['邮件', '邮箱'], icon: AntdIcons.MailOutlined },
  { name: 'MailTwoTone', aliases: ['邮件', '邮箱'], icon: AntdIcons.MailTwoTone },
  { name: 'ManOutlined', aliases: ['男', '男性'], icon: AntdIcons.ManOutlined },
  { name: 'MastodonFilled', aliases: [], icon: AntdIcons.MastodonFilled },
  {
    name: 'MedicineBoxFilled',
    aliases: ['医疗', '医药', '药', '盒子', '箱子'],
    icon: AntdIcons.MedicineBoxFilled,
  },
  {
    name: 'MedicineBoxOutlined',
    aliases: ['医疗', '医药', '药', '盒子', '箱子'],
    icon: AntdIcons.MedicineBoxOutlined,
  },
  {
    name: 'MedicineBoxTwoTone',
    aliases: ['医疗', '医药', '药', '盒子', '箱子'],
    icon: AntdIcons.MedicineBoxTwoTone,
  },
  { name: 'MediumCircleFilled', aliases: ['Medium'], icon: AntdIcons.MediumCircleFilled },
  { name: 'MediumOutlined', aliases: ['Medium'], icon: AntdIcons.MediumOutlined },
  { name: 'MediumSquareFilled', aliases: ['Medium'], icon: AntdIcons.MediumSquareFilled },
  { name: 'MediumWorkmarkOutlined', aliases: ['Medium'], icon: AntdIcons.MediumWorkmarkOutlined },
  { name: 'MehFilled', aliases: [], icon: AntdIcons.MehFilled },
  { name: 'MehOutlined', aliases: [], icon: AntdIcons.MehOutlined },
  { name: 'MehTwoTone', aliases: [], icon: AntdIcons.MehTwoTone },
  { name: 'MenuFoldOutlined', aliases: ['菜单', '导航'], icon: AntdIcons.MenuFoldOutlined },
  { name: 'MenuOutlined', aliases: ['菜单', '导航'], icon: AntdIcons.MenuOutlined },
  { name: 'MenuUnfoldOutlined', aliases: ['菜单', '导航'], icon: AntdIcons.MenuUnfoldOutlined },
  { name: 'MergeCellsOutlined', aliases: ['合并'], icon: AntdIcons.MergeCellsOutlined },
  { name: 'MergeFilled', aliases: ['合并'], icon: AntdIcons.MergeFilled },
  { name: 'MergeOutlined', aliases: ['合并'], icon: AntdIcons.MergeOutlined },
  { name: 'MessageFilled', aliases: ['消息', '通知'], icon: AntdIcons.MessageFilled },
  { name: 'MessageOutlined', aliases: ['消息', '通知'], icon: AntdIcons.MessageOutlined },
  { name: 'MessageTwoTone', aliases: ['消息', '通知'], icon: AntdIcons.MessageTwoTone },
  {
    name: 'MinusCircleFilled',
    aliases: ['减少', '减号', '折叠'],
    icon: AntdIcons.MinusCircleFilled,
  },
  {
    name: 'MinusCircleOutlined',
    aliases: ['减少', '减号', '折叠'],
    icon: AntdIcons.MinusCircleOutlined,
  },
  {
    name: 'MinusCircleTwoTone',
    aliases: ['减少', '减号', '折叠'],
    icon: AntdIcons.MinusCircleTwoTone,
  },
  { name: 'MinusOutlined', aliases: ['减少', '减号', '折叠'], icon: AntdIcons.MinusOutlined },
  {
    name: 'MinusSquareFilled',
    aliases: ['减少', '减号', '折叠'],
    icon: AntdIcons.MinusSquareFilled,
  },
  {
    name: 'MinusSquareOutlined',
    aliases: ['减少', '减号', '折叠'],
    icon: AntdIcons.MinusSquareOutlined,
  },
  {
    name: 'MinusSquareTwoTone',
    aliases: ['减少', '减号', '折叠'],
    icon: AntdIcons.MinusSquareTwoTone,
  },
  { name: 'MistralFilled', aliases: [], icon: AntdIcons.MistralFilled },
  { name: 'MobileFilled', aliases: ['手机', '移动'], icon: AntdIcons.MobileFilled },
  { name: 'MobileOutlined', aliases: ['手机', '移动'], icon: AntdIcons.MobileOutlined },
  { name: 'MobileTwoTone', aliases: ['手机', '移动'], icon: AntdIcons.MobileTwoTone },
  { name: 'MoneyCollectFilled', aliases: ['金钱', '钱'], icon: AntdIcons.MoneyCollectFilled },
  { name: 'MoneyCollectOutlined', aliases: ['金钱', '钱'], icon: AntdIcons.MoneyCollectOutlined },
  { name: 'MoneyCollectTwoTone', aliases: ['金钱', '钱'], icon: AntdIcons.MoneyCollectTwoTone },
  {
    name: 'MonitorOutlined',
    aliases: ['监控', '监视器', '显示器'],
    icon: AntdIcons.MonitorOutlined,
  },
  { name: 'MoonFilled', aliases: ['月亮', '夜间'], icon: AntdIcons.MoonFilled },
  { name: 'MoonOutlined', aliases: ['月亮', '夜间'], icon: AntdIcons.MoonOutlined },
  { name: 'MoreOutlined', aliases: ['更多'], icon: AntdIcons.MoreOutlined },
  { name: 'MutedFilled', aliases: ['静音'], icon: AntdIcons.MutedFilled },
  { name: 'MutedOutlined', aliases: ['静音'], icon: AntdIcons.MutedOutlined },
  {
    name: 'NodeCollapseOutlined',
    aliases: ['节点', '折叠', '收起'],
    icon: AntdIcons.NodeCollapseOutlined,
  },
  {
    name: 'NodeExpandOutlined',
    aliases: ['节点', '展开', '扩展', '扩大'],
    icon: AntdIcons.NodeExpandOutlined,
  },
  { name: 'NodeIndexOutlined', aliases: ['节点'], icon: AntdIcons.NodeIndexOutlined },
  {
    name: 'NotificationFilled',
    aliases: ['通知', '提醒', '公告'],
    icon: AntdIcons.NotificationFilled,
  },
  {
    name: 'NotificationOutlined',
    aliases: ['通知', '提醒', '公告'],
    icon: AntdIcons.NotificationOutlined,
  },
  {
    name: 'NotificationTwoTone',
    aliases: ['通知', '提醒', '公告'],
    icon: AntdIcons.NotificationTwoTone,
  },
  { name: 'NumberOutlined', aliases: ['数字', '编号'], icon: AntdIcons.NumberOutlined },
  { name: 'OllamaFilled', aliases: [], icon: AntdIcons.OllamaFilled },
  { name: 'OneToOneOutlined', aliases: [], icon: AntdIcons.OneToOneOutlined },
  { name: 'OpenAIFilled', aliases: [], icon: AntdIcons.OpenAIFilled },
  { name: 'OpenAIOutlined', aliases: [], icon: AntdIcons.OpenAIOutlined },
  { name: 'OrderedListOutlined', aliases: ['有序'], icon: AntdIcons.OrderedListOutlined },
  { name: 'PaperClipOutlined', aliases: ['纸', '文档'], icon: AntdIcons.PaperClipOutlined },
  { name: 'PartitionOutlined', aliases: ['分区', '分割'], icon: AntdIcons.PartitionOutlined },
  { name: 'PauseCircleFilled', aliases: ['暂停'], icon: AntdIcons.PauseCircleFilled },
  { name: 'PauseCircleOutlined', aliases: ['暂停'], icon: AntdIcons.PauseCircleOutlined },
  { name: 'PauseCircleTwoTone', aliases: ['暂停'], icon: AntdIcons.PauseCircleTwoTone },
  { name: 'PauseOutlined', aliases: ['暂停'], icon: AntdIcons.PauseOutlined },
  { name: 'PayCircleFilled', aliases: ['支付', '付款'], icon: AntdIcons.PayCircleFilled },
  { name: 'PayCircleOutlined', aliases: ['支付', '付款'], icon: AntdIcons.PayCircleOutlined },
  { name: 'PercentageOutlined', aliases: [], icon: AntdIcons.PercentageOutlined },
  { name: 'PerplexityFilled', aliases: [], icon: AntdIcons.PerplexityFilled },
  { name: 'PhoneFilled', aliases: ['电话', '手机'], icon: AntdIcons.PhoneFilled },
  { name: 'PhoneOutlined', aliases: ['电话', '手机'], icon: AntdIcons.PhoneOutlined },
  { name: 'PhoneTwoTone', aliases: ['电话', '手机'], icon: AntdIcons.PhoneTwoTone },
  { name: 'PicCenterOutlined', aliases: ['图片', '图像'], icon: AntdIcons.PicCenterOutlined },
  {
    name: 'PicLeftOutlined',
    aliases: ['图片', '图像', '左', '向左'],
    icon: AntdIcons.PicLeftOutlined,
  },
  {
    name: 'PicRightOutlined',
    aliases: ['图片', '图像', '右', '向右'],
    icon: AntdIcons.PicRightOutlined,
  },
  { name: 'PictureFilled', aliases: ['图片', '图像'], icon: AntdIcons.PictureFilled },
  { name: 'PictureOutlined', aliases: ['图片', '图像'], icon: AntdIcons.PictureOutlined },
  { name: 'PictureTwoTone', aliases: ['图片', '图像'], icon: AntdIcons.PictureTwoTone },
  {
    name: 'PieChartFilled',
    aliases: ['饼图', '圆形', '图表', '统计'],
    icon: AntdIcons.PieChartFilled,
  },
  {
    name: 'PieChartOutlined',
    aliases: ['饼图', '圆形', '图表', '统计'],
    icon: AntdIcons.PieChartOutlined,
  },
  {
    name: 'PieChartTwoTone',
    aliases: ['饼图', '圆形', '图表', '统计'],
    icon: AntdIcons.PieChartTwoTone,
  },
  { name: 'PinterestFilled', aliases: [], icon: AntdIcons.PinterestFilled },
  { name: 'PinterestOutlined', aliases: [], icon: AntdIcons.PinterestOutlined },
  { name: 'PlayCircleFilled', aliases: ['播放'], icon: AntdIcons.PlayCircleFilled },
  { name: 'PlayCircleOutlined', aliases: ['播放'], icon: AntdIcons.PlayCircleOutlined },
  { name: 'PlayCircleTwoTone', aliases: ['播放'], icon: AntdIcons.PlayCircleTwoTone },
  { name: 'PlaySquareFilled', aliases: ['播放'], icon: AntdIcons.PlaySquareFilled },
  { name: 'PlaySquareOutlined', aliases: ['播放'], icon: AntdIcons.PlaySquareOutlined },
  { name: 'PlaySquareTwoTone', aliases: ['播放'], icon: AntdIcons.PlaySquareTwoTone },
  {
    name: 'PlusCircleFilled',
    aliases: ['添加', '加号', '新增', '增加'],
    icon: AntdIcons.PlusCircleFilled,
  },
  {
    name: 'PlusCircleOutlined',
    aliases: ['添加', '加号', '新增', '增加'],
    icon: AntdIcons.PlusCircleOutlined,
  },
  {
    name: 'PlusCircleTwoTone',
    aliases: ['添加', '加号', '新增', '增加'],
    icon: AntdIcons.PlusCircleTwoTone,
  },
  { name: 'PlusOutlined', aliases: ['添加', '加号', '新增', '增加'], icon: AntdIcons.PlusOutlined },
  {
    name: 'PlusSquareFilled',
    aliases: ['添加', '加号', '新增', '增加'],
    icon: AntdIcons.PlusSquareFilled,
  },
  {
    name: 'PlusSquareOutlined',
    aliases: ['添加', '加号', '新增', '增加'],
    icon: AntdIcons.PlusSquareOutlined,
  },
  {
    name: 'PlusSquareTwoTone',
    aliases: ['添加', '加号', '新增', '增加'],
    icon: AntdIcons.PlusSquareTwoTone,
  },
  { name: 'PoundCircleFilled', aliases: ['英镑'], icon: AntdIcons.PoundCircleFilled },
  { name: 'PoundCircleOutlined', aliases: ['英镑'], icon: AntdIcons.PoundCircleOutlined },
  { name: 'PoundCircleTwoTone', aliases: ['英镑'], icon: AntdIcons.PoundCircleTwoTone },
  { name: 'PoundOutlined', aliases: ['英镑'], icon: AntdIcons.PoundOutlined },
  { name: 'PoweroffOutlined', aliases: [], icon: AntdIcons.PoweroffOutlined },
  { name: 'PrinterFilled', aliases: [], icon: AntdIcons.PrinterFilled },
  { name: 'PrinterOutlined', aliases: [], icon: AntdIcons.PrinterOutlined },
  { name: 'PrinterTwoTone', aliases: [], icon: AntdIcons.PrinterTwoTone },
  { name: 'ProductFilled', aliases: [], icon: AntdIcons.ProductFilled },
  { name: 'ProductOutlined', aliases: [], icon: AntdIcons.ProductOutlined },
  { name: 'ProfileFilled', aliases: ['概要', '档案', '配置文件'], icon: AntdIcons.ProfileFilled },
  {
    name: 'ProfileOutlined',
    aliases: ['概要', '档案', '配置文件'],
    icon: AntdIcons.ProfileOutlined,
  },
  { name: 'ProfileTwoTone', aliases: ['概要', '档案', '配置文件'], icon: AntdIcons.ProfileTwoTone },
  { name: 'ProjectFilled', aliases: ['项目'], icon: AntdIcons.ProjectFilled },
  { name: 'ProjectOutlined', aliases: ['项目'], icon: AntdIcons.ProjectOutlined },
  { name: 'ProjectTwoTone', aliases: ['项目'], icon: AntdIcons.ProjectTwoTone },
  {
    name: 'PropertySafetyFilled',
    aliases: ['属性', '安全', '防护'],
    icon: AntdIcons.PropertySafetyFilled,
  },
  {
    name: 'PropertySafetyOutlined',
    aliases: ['属性', '安全', '防护'],
    icon: AntdIcons.PropertySafetyOutlined,
  },
  {
    name: 'PropertySafetyTwoTone',
    aliases: ['属性', '安全', '防护'],
    icon: AntdIcons.PropertySafetyTwoTone,
  },
  { name: 'PullRequestOutlined', aliases: ['拉取'], icon: AntdIcons.PullRequestOutlined },
  { name: 'PushpinFilled', aliases: ['图钉', '置顶'], icon: AntdIcons.PushpinFilled },
  { name: 'PushpinOutlined', aliases: ['图钉', '置顶'], icon: AntdIcons.PushpinOutlined },
  { name: 'PushpinTwoTone', aliases: ['图钉', '置顶'], icon: AntdIcons.PushpinTwoTone },
  { name: 'PythonOutlined', aliases: [], icon: AntdIcons.PythonOutlined },
  { name: 'QqCircleFilled', aliases: [], icon: AntdIcons.QqCircleFilled },
  { name: 'QqOutlined', aliases: [], icon: AntdIcons.QqOutlined },
  { name: 'QqSquareFilled', aliases: [], icon: AntdIcons.QqSquareFilled },
  { name: 'QrcodeOutlined', aliases: ['二维码', 'QR码'], icon: AntdIcons.QrcodeOutlined },
  { name: 'QuestionCircleFilled', aliases: ['问题', '帮助'], icon: AntdIcons.QuestionCircleFilled },
  {
    name: 'QuestionCircleOutlined',
    aliases: ['问题', '帮助'],
    icon: AntdIcons.QuestionCircleOutlined,
  },
  {
    name: 'QuestionCircleTwoTone',
    aliases: ['问题', '帮助'],
    icon: AntdIcons.QuestionCircleTwoTone,
  },
  { name: 'QuestionOutlined', aliases: ['问题', '帮助'], icon: AntdIcons.QuestionOutlined },
  { name: 'QwenFilled', aliases: [], icon: AntdIcons.QwenFilled },
  { name: 'RadarChartOutlined', aliases: ['图表', '统计'], icon: AntdIcons.RadarChartOutlined },
  { name: 'RadiusBottomleftOutlined', aliases: ['圆角'], icon: AntdIcons.RadiusBottomleftOutlined },
  {
    name: 'RadiusBottomrightOutlined',
    aliases: ['圆角'],
    icon: AntdIcons.RadiusBottomrightOutlined,
  },
  {
    name: 'RadiusSettingOutlined',
    aliases: ['圆角', '设置', '配置', '选项'],
    icon: AntdIcons.RadiusSettingOutlined,
  },
  { name: 'RadiusUpleftOutlined', aliases: ['圆角'], icon: AntdIcons.RadiusUpleftOutlined },
  { name: 'RadiusUprightOutlined', aliases: ['圆角'], icon: AntdIcons.RadiusUprightOutlined },
  { name: 'ReadFilled', aliases: ['阅读', '读取'], icon: AntdIcons.ReadFilled },
  { name: 'ReadOutlined', aliases: ['阅读', '读取'], icon: AntdIcons.ReadOutlined },
  { name: 'ReconciliationFilled', aliases: ['核对', '对账'], icon: AntdIcons.ReconciliationFilled },
  {
    name: 'ReconciliationOutlined',
    aliases: ['核对', '对账'],
    icon: AntdIcons.ReconciliationOutlined,
  },
  {
    name: 'ReconciliationTwoTone',
    aliases: ['核对', '对账'],
    icon: AntdIcons.ReconciliationTwoTone,
  },
  { name: 'RedEnvelopeFilled', aliases: [], icon: AntdIcons.RedEnvelopeFilled },
  { name: 'RedEnvelopeOutlined', aliases: [], icon: AntdIcons.RedEnvelopeOutlined },
  { name: 'RedEnvelopeTwoTone', aliases: [], icon: AntdIcons.RedEnvelopeTwoTone },
  { name: 'RedditCircleFilled', aliases: [], icon: AntdIcons.RedditCircleFilled },
  { name: 'RedditOutlined', aliases: [], icon: AntdIcons.RedditOutlined },
  { name: 'RedditSquareFilled', aliases: [], icon: AntdIcons.RedditSquareFilled },
  { name: 'RedoOutlined', aliases: ['重做', '恢复'], icon: AntdIcons.RedoOutlined },
  { name: 'ReloadOutlined', aliases: ['刷新', '重新加载'], icon: AntdIcons.ReloadOutlined },
  { name: 'ReplicateFilled', aliases: [], icon: AntdIcons.ReplicateFilled },
  { name: 'RestFilled', aliases: [], icon: AntdIcons.RestFilled },
  { name: 'RestOutlined', aliases: [], icon: AntdIcons.RestOutlined },
  { name: 'RestTwoTone', aliases: [], icon: AntdIcons.RestTwoTone },
  { name: 'RetweetOutlined', aliases: [], icon: AntdIcons.RetweetOutlined },
  { name: 'RightCircleFilled', aliases: ['右', '向右'], icon: AntdIcons.RightCircleFilled },
  { name: 'RightCircleOutlined', aliases: ['右', '向右'], icon: AntdIcons.RightCircleOutlined },
  { name: 'RightCircleTwoTone', aliases: ['右', '向右'], icon: AntdIcons.RightCircleTwoTone },
  { name: 'RightOutlined', aliases: ['右', '向右'], icon: AntdIcons.RightOutlined },
  { name: 'RightSquareFilled', aliases: ['右', '向右'], icon: AntdIcons.RightSquareFilled },
  { name: 'RightSquareOutlined', aliases: ['右', '向右'], icon: AntdIcons.RightSquareOutlined },
  { name: 'RightSquareTwoTone', aliases: ['右', '向右'], icon: AntdIcons.RightSquareTwoTone },
  { name: 'RiseOutlined', aliases: ['上升', '增长'], icon: AntdIcons.RiseOutlined },
  { name: 'RobotFilled', aliases: ['机器人', 'AI', '自动化'], icon: AntdIcons.RobotFilled },
  { name: 'RobotOutlined', aliases: ['机器人', 'AI', '自动化'], icon: AntdIcons.RobotOutlined },
  { name: 'RocketFilled', aliases: ['火箭', '发射', '启动'], icon: AntdIcons.RocketFilled },
  { name: 'RocketOutlined', aliases: ['火箭', '发射', '启动'], icon: AntdIcons.RocketOutlined },
  { name: 'RocketTwoTone', aliases: ['火箭', '发射', '启动'], icon: AntdIcons.RocketTwoTone },
  { name: 'RollbackOutlined', aliases: ['回滚', '撤销'], icon: AntdIcons.RollbackOutlined },
  { name: 'RotateLeftOutlined', aliases: ['左', '向左'], icon: AntdIcons.RotateLeftOutlined },
  { name: 'RotateRightOutlined', aliases: ['右', '向右'], icon: AntdIcons.RotateRightOutlined },
  { name: 'RubyOutlined', aliases: [], icon: AntdIcons.RubyOutlined },
  {
    name: 'SafetyCertificateFilled',
    aliases: ['安全', '防护'],
    icon: AntdIcons.SafetyCertificateFilled,
  },
  {
    name: 'SafetyCertificateOutlined',
    aliases: ['安全', '防护'],
    icon: AntdIcons.SafetyCertificateOutlined,
  },
  {
    name: 'SafetyCertificateTwoTone',
    aliases: ['安全', '防护'],
    icon: AntdIcons.SafetyCertificateTwoTone,
  },
  { name: 'SafetyOutlined', aliases: ['安全', '防护'], icon: AntdIcons.SafetyOutlined },
  { name: 'SaveFilled', aliases: ['保存', '存储'], icon: AntdIcons.SaveFilled },
  { name: 'SaveOutlined', aliases: ['保存', '存储'], icon: AntdIcons.SaveOutlined },
  { name: 'SaveTwoTone', aliases: ['保存', '存储'], icon: AntdIcons.SaveTwoTone },
  { name: 'ScanOutlined', aliases: ['扫描'], icon: AntdIcons.ScanOutlined },
  {
    name: 'ScheduleFilled',
    aliases: ['计划', '日程', '排班', '定时'],
    icon: AntdIcons.ScheduleFilled,
  },
  {
    name: 'ScheduleOutlined',
    aliases: ['计划', '日程', '排班', '定时'],
    icon: AntdIcons.ScheduleOutlined,
  },
  {
    name: 'ScheduleTwoTone',
    aliases: ['计划', '日程', '排班', '定时'],
    icon: AntdIcons.ScheduleTwoTone,
  },
  { name: 'ScissorOutlined', aliases: ['剪刀', '裁剪'], icon: AntdIcons.ScissorOutlined },
  { name: 'SearchOutlined', aliases: ['搜索', '查找', '查询'], icon: AntdIcons.SearchOutlined },
  { name: 'SecurityScanFilled', aliases: ['扫描'], icon: AntdIcons.SecurityScanFilled },
  { name: 'SecurityScanOutlined', aliases: ['扫描'], icon: AntdIcons.SecurityScanOutlined },
  { name: 'SecurityScanTwoTone', aliases: ['扫描'], icon: AntdIcons.SecurityScanTwoTone },
  { name: 'SelectOutlined', aliases: ['选择', '选取'], icon: AntdIcons.SelectOutlined },
  { name: 'SendOutlined', aliases: ['发送'], icon: AntdIcons.SendOutlined },
  { name: 'SettingFilled', aliases: ['设置', '配置', '选项'], icon: AntdIcons.SettingFilled },
  { name: 'SettingOutlined', aliases: ['设置', '配置', '选项'], icon: AntdIcons.SettingOutlined },
  { name: 'SettingTwoTone', aliases: ['设置', '配置', '选项'], icon: AntdIcons.SettingTwoTone },
  { name: 'ShakeOutlined', aliases: [], icon: AntdIcons.ShakeOutlined },
  { name: 'ShareAltOutlined', aliases: ['分享', '共享'], icon: AntdIcons.ShareAltOutlined },
  { name: 'ShopFilled', aliases: ['商店', '商城'], icon: AntdIcons.ShopFilled },
  { name: 'ShopOutlined', aliases: ['商店', '商城'], icon: AntdIcons.ShopOutlined },
  { name: 'ShopTwoTone', aliases: ['商店', '商城'], icon: AntdIcons.ShopTwoTone },
  { name: 'ShoppingCartOutlined', aliases: ['购物', '购买'], icon: AntdIcons.ShoppingCartOutlined },
  { name: 'ShoppingFilled', aliases: ['购物', '购买'], icon: AntdIcons.ShoppingFilled },
  { name: 'ShoppingOutlined', aliases: ['购物', '购买'], icon: AntdIcons.ShoppingOutlined },
  { name: 'ShoppingTwoTone', aliases: ['购物', '购买'], icon: AntdIcons.ShoppingTwoTone },
  { name: 'ShrinkOutlined', aliases: ['收缩', '缩小'], icon: AntdIcons.ShrinkOutlined },
  { name: 'SignalFilled', aliases: [], icon: AntdIcons.SignalFilled },
  { name: 'SignatureFilled', aliases: [], icon: AntdIcons.SignatureFilled },
  { name: 'SignatureOutlined', aliases: [], icon: AntdIcons.SignatureOutlined },
  { name: 'SisternodeOutlined', aliases: [], icon: AntdIcons.SisternodeOutlined },
  { name: 'SketchCircleFilled', aliases: ['设计', '草图'], icon: AntdIcons.SketchCircleFilled },
  { name: 'SketchOutlined', aliases: ['设计', '草图'], icon: AntdIcons.SketchOutlined },
  { name: 'SketchSquareFilled', aliases: ['设计', '草图'], icon: AntdIcons.SketchSquareFilled },
  { name: 'SkinFilled', aliases: ['皮肤', '主题'], icon: AntdIcons.SkinFilled },
  { name: 'SkinOutlined', aliases: ['皮肤', '主题'], icon: AntdIcons.SkinOutlined },
  { name: 'SkinTwoTone', aliases: ['皮肤', '主题'], icon: AntdIcons.SkinTwoTone },
  { name: 'SkypeFilled', aliases: [], icon: AntdIcons.SkypeFilled },
  { name: 'SkypeOutlined', aliases: [], icon: AntdIcons.SkypeOutlined },
  { name: 'SlackCircleFilled', aliases: ['Slack'], icon: AntdIcons.SlackCircleFilled },
  { name: 'SlackOutlined', aliases: ['Slack'], icon: AntdIcons.SlackOutlined },
  { name: 'SlackSquareFilled', aliases: ['Slack'], icon: AntdIcons.SlackSquareFilled },
  { name: 'SlackSquareOutlined', aliases: ['Slack'], icon: AntdIcons.SlackSquareOutlined },
  { name: 'SlidersFilled', aliases: [], icon: AntdIcons.SlidersFilled },
  { name: 'SlidersOutlined', aliases: [], icon: AntdIcons.SlidersOutlined },
  { name: 'SlidersTwoTone', aliases: [], icon: AntdIcons.SlidersTwoTone },
  { name: 'SmallDashOutlined', aliases: [], icon: AntdIcons.SmallDashOutlined },
  { name: 'SmileFilled', aliases: ['笑脸', '满意', '高兴'], icon: AntdIcons.SmileFilled },
  { name: 'SmileOutlined', aliases: ['笑脸', '满意', '高兴'], icon: AntdIcons.SmileOutlined },
  { name: 'SmileTwoTone', aliases: ['笑脸', '满意', '高兴'], icon: AntdIcons.SmileTwoTone },
  { name: 'SnapchatFilled', aliases: [], icon: AntdIcons.SnapchatFilled },
  { name: 'SnippetsFilled', aliases: [], icon: AntdIcons.SnippetsFilled },
  { name: 'SnippetsOutlined', aliases: [], icon: AntdIcons.SnippetsOutlined },
  { name: 'SnippetsTwoTone', aliases: [], icon: AntdIcons.SnippetsTwoTone },
  { name: 'SolutionOutlined', aliases: ['解决方案', '方案'], icon: AntdIcons.SolutionOutlined },
  { name: 'SortAscendingOutlined', aliases: ['排序'], icon: AntdIcons.SortAscendingOutlined },
  { name: 'SortDescendingOutlined', aliases: ['排序'], icon: AntdIcons.SortDescendingOutlined },
  { name: 'SoundFilled', aliases: ['声音', '音频', '音量'], icon: AntdIcons.SoundFilled },
  { name: 'SoundOutlined', aliases: ['声音', '音频', '音量'], icon: AntdIcons.SoundOutlined },
  { name: 'SoundTwoTone', aliases: ['声音', '音频', '音量'], icon: AntdIcons.SoundTwoTone },
  { name: 'SplitCellsOutlined', aliases: ['分割', '拆分'], icon: AntdIcons.SplitCellsOutlined },
  { name: 'SpotifyFilled', aliases: [], icon: AntdIcons.SpotifyFilled },
  { name: 'SpotifyOutlined', aliases: [], icon: AntdIcons.SpotifyOutlined },
  { name: 'StarFilled', aliases: ['星', '收藏', '评分'], icon: AntdIcons.StarFilled },
  { name: 'StarOutlined', aliases: ['星', '收藏', '评分'], icon: AntdIcons.StarOutlined },
  { name: 'StarTwoTone', aliases: ['星', '收藏', '评分'], icon: AntdIcons.StarTwoTone },
  { name: 'StepBackwardFilled', aliases: ['后退'], icon: AntdIcons.StepBackwardFilled },
  { name: 'StepBackwardOutlined', aliases: ['后退'], icon: AntdIcons.StepBackwardOutlined },
  { name: 'StepForwardFilled', aliases: ['前进'], icon: AntdIcons.StepForwardFilled },
  { name: 'StepForwardOutlined', aliases: ['前进'], icon: AntdIcons.StepForwardOutlined },
  { name: 'StockOutlined', aliases: ['股票', '库存'], icon: AntdIcons.StockOutlined },
  { name: 'StopFilled', aliases: ['停止', '禁止'], icon: AntdIcons.StopFilled },
  { name: 'StopOutlined', aliases: ['停止', '禁止'], icon: AntdIcons.StopOutlined },
  { name: 'StopTwoTone', aliases: ['停止', '禁止'], icon: AntdIcons.StopTwoTone },
  { name: 'StrikethroughOutlined', aliases: ['删除线'], icon: AntdIcons.StrikethroughOutlined },
  { name: 'SubnodeOutlined', aliases: [], icon: AntdIcons.SubnodeOutlined },
  { name: 'SunFilled', aliases: ['太阳', '晴天'], icon: AntdIcons.SunFilled },
  { name: 'SunOutlined', aliases: ['太阳', '晴天'], icon: AntdIcons.SunOutlined },
  {
    name: 'SwapLeftOutlined',
    aliases: ['交换', '互换', '左', '向左'],
    icon: AntdIcons.SwapLeftOutlined,
  },
  { name: 'SwapOutlined', aliases: ['交换', '互换'], icon: AntdIcons.SwapOutlined },
  {
    name: 'SwapRightOutlined',
    aliases: ['交换', '互换', '右', '向右'],
    icon: AntdIcons.SwapRightOutlined,
  },
  { name: 'SwitcherFilled', aliases: [], icon: AntdIcons.SwitcherFilled },
  { name: 'SwitcherOutlined', aliases: [], icon: AntdIcons.SwitcherOutlined },
  { name: 'SwitcherTwoTone', aliases: [], icon: AntdIcons.SwitcherTwoTone },
  { name: 'SyncOutlined', aliases: ['同步', '刷新'], icon: AntdIcons.SyncOutlined },
  { name: 'TableOutlined', aliases: ['表格', '数据表'], icon: AntdIcons.TableOutlined },
  { name: 'TabletFilled', aliases: ['平板', '平板电脑'], icon: AntdIcons.TabletFilled },
  { name: 'TabletOutlined', aliases: ['平板', '平板电脑'], icon: AntdIcons.TabletOutlined },
  { name: 'TabletTwoTone', aliases: ['平板', '平板电脑'], icon: AntdIcons.TabletTwoTone },
  { name: 'TagFilled', aliases: ['标签', '标记'], icon: AntdIcons.TagFilled },
  { name: 'TagOutlined', aliases: ['标签', '标记'], icon: AntdIcons.TagOutlined },
  { name: 'TagTwoTone', aliases: ['标签', '标记'], icon: AntdIcons.TagTwoTone },
  { name: 'TagsFilled', aliases: [], icon: AntdIcons.TagsFilled },
  { name: 'TagsOutlined', aliases: [], icon: AntdIcons.TagsOutlined },
  { name: 'TagsTwoTone', aliases: [], icon: AntdIcons.TagsTwoTone },
  { name: 'TaobaoCircleFilled', aliases: ['淘宝'], icon: AntdIcons.TaobaoCircleFilled },
  { name: 'TaobaoCircleOutlined', aliases: ['淘宝'], icon: AntdIcons.TaobaoCircleOutlined },
  { name: 'TaobaoOutlined', aliases: ['淘宝'], icon: AntdIcons.TaobaoOutlined },
  { name: 'TaobaoSquareFilled', aliases: ['淘宝'], icon: AntdIcons.TaobaoSquareFilled },
  { name: 'TeamOutlined', aliases: ['团队', '群组', '成员'], icon: AntdIcons.TeamOutlined },
  { name: 'TelegramFilled', aliases: [], icon: AntdIcons.TelegramFilled },
  { name: 'ThreadsFilled', aliases: [], icon: AntdIcons.ThreadsFilled },
  {
    name: 'ThunderboltFilled',
    aliases: ['闪电', '快速', '高速'],
    icon: AntdIcons.ThunderboltFilled,
  },
  {
    name: 'ThunderboltOutlined',
    aliases: ['闪电', '快速', '高速'],
    icon: AntdIcons.ThunderboltOutlined,
  },
  {
    name: 'ThunderboltTwoTone',
    aliases: ['闪电', '快速', '高速'],
    icon: AntdIcons.ThunderboltTwoTone,
  },
  { name: 'TikTokFilled', aliases: [], icon: AntdIcons.TikTokFilled },
  { name: 'TikTokOutlined', aliases: [], icon: AntdIcons.TikTokOutlined },
  { name: 'ToTopOutlined', aliases: [], icon: AntdIcons.ToTopOutlined },
  { name: 'ToolFilled', aliases: ['工具'], icon: AntdIcons.ToolFilled },
  { name: 'ToolOutlined', aliases: ['工具'], icon: AntdIcons.ToolOutlined },
  { name: 'ToolTwoTone', aliases: ['工具'], icon: AntdIcons.ToolTwoTone },
  { name: 'TrademarkCircleFilled', aliases: ['商标'], icon: AntdIcons.TrademarkCircleFilled },
  { name: 'TrademarkCircleOutlined', aliases: ['商标'], icon: AntdIcons.TrademarkCircleOutlined },
  { name: 'TrademarkCircleTwoTone', aliases: ['商标'], icon: AntdIcons.TrademarkCircleTwoTone },
  { name: 'TrademarkOutlined', aliases: ['商标'], icon: AntdIcons.TrademarkOutlined },
  { name: 'TransactionOutlined', aliases: ['交易', '事务'], icon: AntdIcons.TransactionOutlined },
  { name: 'TranslationOutlined', aliases: ['翻译', '语言'], icon: AntdIcons.TranslationOutlined },
  { name: 'TrophyFilled', aliases: ['奖杯', '成就'], icon: AntdIcons.TrophyFilled },
  { name: 'TrophyOutlined', aliases: ['奖杯', '成就'], icon: AntdIcons.TrophyOutlined },
  { name: 'TrophyTwoTone', aliases: ['奖杯', '成就'], icon: AntdIcons.TrophyTwoTone },
  { name: 'TruckFilled', aliases: [], icon: AntdIcons.TruckFilled },
  { name: 'TruckOutlined', aliases: [], icon: AntdIcons.TruckOutlined },
  { name: 'TwitchFilled', aliases: [], icon: AntdIcons.TwitchFilled },
  { name: 'TwitchOutlined', aliases: [], icon: AntdIcons.TwitchOutlined },
  { name: 'TwitterCircleFilled', aliases: ['Twitter'], icon: AntdIcons.TwitterCircleFilled },
  { name: 'TwitterOutlined', aliases: ['Twitter'], icon: AntdIcons.TwitterOutlined },
  { name: 'TwitterSquareFilled', aliases: ['Twitter'], icon: AntdIcons.TwitterSquareFilled },
  { name: 'UnderlineOutlined', aliases: ['下划线'], icon: AntdIcons.UnderlineOutlined },
  { name: 'UndoOutlined', aliases: ['撤销'], icon: AntdIcons.UndoOutlined },
  { name: 'UngroupOutlined', aliases: [], icon: AntdIcons.UngroupOutlined },
  { name: 'UnlockFilled', aliases: ['解锁', '开锁'], icon: AntdIcons.UnlockFilled },
  { name: 'UnlockOutlined', aliases: ['解锁', '开锁'], icon: AntdIcons.UnlockOutlined },
  { name: 'UnlockTwoTone', aliases: ['解锁', '开锁'], icon: AntdIcons.UnlockTwoTone },
  { name: 'UnorderedListOutlined', aliases: ['无序'], icon: AntdIcons.UnorderedListOutlined },
  { name: 'UpCircleFilled', aliases: ['上', '向上'], icon: AntdIcons.UpCircleFilled },
  { name: 'UpCircleOutlined', aliases: ['上', '向上'], icon: AntdIcons.UpCircleOutlined },
  { name: 'UpCircleTwoTone', aliases: ['上', '向上'], icon: AntdIcons.UpCircleTwoTone },
  { name: 'UpOutlined', aliases: ['上', '向上'], icon: AntdIcons.UpOutlined },
  { name: 'UpSquareFilled', aliases: ['上', '向上'], icon: AntdIcons.UpSquareFilled },
  { name: 'UpSquareOutlined', aliases: ['上', '向上'], icon: AntdIcons.UpSquareOutlined },
  { name: 'UpSquareTwoTone', aliases: ['上', '向上'], icon: AntdIcons.UpSquareTwoTone },
  { name: 'UploadOutlined', aliases: ['上传'], icon: AntdIcons.UploadOutlined },
  { name: 'UsbFilled', aliases: ['USB'], icon: AntdIcons.UsbFilled },
  { name: 'UsbOutlined', aliases: ['USB'], icon: AntdIcons.UsbOutlined },
  { name: 'UsbTwoTone', aliases: ['USB'], icon: AntdIcons.UsbTwoTone },
  {
    name: 'UserAddOutlined',
    aliases: ['用户', '人员', '账号', '个人', '添加', '新增', '增加'],
    icon: AntdIcons.UserAddOutlined,
  },
  {
    name: 'UserDeleteOutlined',
    aliases: ['用户', '人员', '账号', '个人', '删除', '移除', '清除'],
    icon: AntdIcons.UserDeleteOutlined,
  },
  { name: 'UserOutlined', aliases: ['用户', '人员', '账号', '个人'], icon: AntdIcons.UserOutlined },
  {
    name: 'UserSwitchOutlined',
    aliases: ['用户', '人员', '账号', '个人', '开关', '切换'],
    icon: AntdIcons.UserSwitchOutlined,
  },
  {
    name: 'UsergroupAddOutlined',
    aliases: ['添加', '新增', '增加'],
    icon: AntdIcons.UsergroupAddOutlined,
  },
  {
    name: 'UsergroupDeleteOutlined',
    aliases: ['删除', '移除', '清除'],
    icon: AntdIcons.UsergroupDeleteOutlined,
  },
  { name: 'VerifiedOutlined', aliases: ['已验证', '认证'], icon: AntdIcons.VerifiedOutlined },
  {
    name: 'VerticalAlignBottomOutlined',
    aliases: ['垂直', '对齐'],
    icon: AntdIcons.VerticalAlignBottomOutlined,
  },
  {
    name: 'VerticalAlignMiddleOutlined',
    aliases: ['垂直', '对齐'],
    icon: AntdIcons.VerticalAlignMiddleOutlined,
  },
  {
    name: 'VerticalAlignTopOutlined',
    aliases: ['垂直', '对齐'],
    icon: AntdIcons.VerticalAlignTopOutlined,
  },
  {
    name: 'VerticalLeftOutlined',
    aliases: ['垂直', '左', '向左'],
    icon: AntdIcons.VerticalLeftOutlined,
  },
  {
    name: 'VerticalRightOutlined',
    aliases: ['垂直', '右', '向右'],
    icon: AntdIcons.VerticalRightOutlined,
  },
  {
    name: 'VideoCameraAddOutlined',
    aliases: ['视频', '相机', '拍照', '摄像', '添加', '新增', '增加'],
    icon: AntdIcons.VideoCameraAddOutlined,
  },
  {
    name: 'VideoCameraFilled',
    aliases: ['视频', '相机', '拍照', '摄像'],
    icon: AntdIcons.VideoCameraFilled,
  },
  {
    name: 'VideoCameraOutlined',
    aliases: ['视频', '相机', '拍照', '摄像'],
    icon: AntdIcons.VideoCameraOutlined,
  },
  {
    name: 'VideoCameraTwoTone',
    aliases: ['视频', '相机', '拍照', '摄像'],
    icon: AntdIcons.VideoCameraTwoTone,
  },
  { name: 'WalletFilled', aliases: ['钱包'], icon: AntdIcons.WalletFilled },
  { name: 'WalletOutlined', aliases: ['钱包'], icon: AntdIcons.WalletOutlined },
  { name: 'WalletTwoTone', aliases: ['钱包'], icon: AntdIcons.WalletTwoTone },
  { name: 'WarningFilled', aliases: ['警告', '注意', '告警'], icon: AntdIcons.WarningFilled },
  { name: 'WarningOutlined', aliases: ['警告', '注意', '告警'], icon: AntdIcons.WarningOutlined },
  { name: 'WarningTwoTone', aliases: ['警告', '注意', '告警'], icon: AntdIcons.WarningTwoTone },
  { name: 'WechatFilled', aliases: ['微信'], icon: AntdIcons.WechatFilled },
  { name: 'WechatOutlined', aliases: ['微信'], icon: AntdIcons.WechatOutlined },
  { name: 'WechatWorkFilled', aliases: ['微信'], icon: AntdIcons.WechatWorkFilled },
  { name: 'WechatWorkOutlined', aliases: ['微信'], icon: AntdIcons.WechatWorkOutlined },
  { name: 'WeiboCircleFilled', aliases: ['微博'], icon: AntdIcons.WeiboCircleFilled },
  { name: 'WeiboCircleOutlined', aliases: ['微博'], icon: AntdIcons.WeiboCircleOutlined },
  { name: 'WeiboOutlined', aliases: ['微博'], icon: AntdIcons.WeiboOutlined },
  { name: 'WeiboSquareFilled', aliases: ['微博'], icon: AntdIcons.WeiboSquareFilled },
  { name: 'WeiboSquareOutlined', aliases: ['微博'], icon: AntdIcons.WeiboSquareOutlined },
  { name: 'WhatsAppOutlined', aliases: [], icon: AntdIcons.WhatsAppOutlined },
  { name: 'WifiOutlined', aliases: ['WiFi', '无线网络', '网络'], icon: AntdIcons.WifiOutlined },
  { name: 'WindowsFilled', aliases: ['Windows', '窗口'], icon: AntdIcons.WindowsFilled },
  { name: 'WindowsOutlined', aliases: ['Windows', '窗口'], icon: AntdIcons.WindowsOutlined },
  { name: 'WomanOutlined', aliases: ['女', '女性'], icon: AntdIcons.WomanOutlined },
  { name: 'XFilled', aliases: [], icon: AntdIcons.XFilled },
  { name: 'XOutlined', aliases: [], icon: AntdIcons.XOutlined },
  { name: 'YahooFilled', aliases: [], icon: AntdIcons.YahooFilled },
  { name: 'YahooOutlined', aliases: [], icon: AntdIcons.YahooOutlined },
  { name: 'YoutubeFilled', aliases: [], icon: AntdIcons.YoutubeFilled },
  { name: 'YoutubeOutlined', aliases: [], icon: AntdIcons.YoutubeOutlined },
  { name: 'YuqueFilled', aliases: ['语雀'], icon: AntdIcons.YuqueFilled },
  { name: 'YuqueOutlined', aliases: ['语雀'], icon: AntdIcons.YuqueOutlined },
  { name: 'ZhihuCircleFilled', aliases: ['知乎'], icon: AntdIcons.ZhihuCircleFilled },
  { name: 'ZhihuOutlined', aliases: ['知乎'], icon: AntdIcons.ZhihuOutlined },
  { name: 'ZhihuSquareFilled', aliases: ['知乎'], icon: AntdIcons.ZhihuSquareFilled },
  { name: 'ZoomInOutlined', aliases: ['缩放', '放大缩小'], icon: AntdIcons.ZoomInOutlined },
  { name: 'ZoomOutOutlined', aliases: ['缩放', '放大缩小'], icon: AntdIcons.ZoomOutOutlined },
];

/** 按组件名快速查找 */
export const iconCatalogMap: ReadonlyMap<string, IconCatalogItem> = new Map(
  iconCatalog.map((item) => [item.name, item]),
);

/**
 * 将图标名解析为可渲染的 React 元素。
 * 未知名称或空值回退到 AppstoreOutlined，但不修改原始字符串。
 */
export function getIcon(iconName?: string): React.ReactElement | undefined {
  if (!iconName) return undefined;
  const item = iconCatalogMap.get(iconName);
  const IconComp = item ? item.icon : AntdIcons.AppstoreOutlined;
  return React.createElement(IconComp);
}

/** 风格后缀 */
const STYLE_SUFFIXES = ['Outlined', 'Filled', 'TwoTone'] as const;

/**
 * 按关键词过滤图标目录。
 * 匹配规则（任一命中即返回）：
 *   1. 完整组件名（大小写不敏感）
 *   2. 去除风格后缀后的名称（大小写不敏感）
 *   3. 中文别名包含匹配
 */
export function filterIconCatalog(
  catalog: readonly IconCatalogItem[],
  keyword: string,
): IconCatalogItem[] {
  const kw = keyword.trim();
  if (!kw) return [...catalog];
  const lower = kw.toLowerCase();
  return catalog.filter((item) => {
    if (item.name.toLowerCase().includes(lower)) return true;
    const baseName = STYLE_SUFFIXES.reduce((n, s) => n.replace(new RegExp(s + '$'), ''), item.name);
    if (baseName.toLowerCase().includes(lower)) return true;
    return item.aliases.some((a) => a.includes(kw));
  });
}
